module.exports = {
  apps: [
    {
      name: 'sanliurfa',
      script: './dist/server/entry.mjs',
      instances: 'max',
      exec_mode: 'cluster',
      wait_ready: true,
      listen_timeout: 3000,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
        PORT: 4321,
        LOG_LEVEL: 'info',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4321,
        LOG_LEVEL: 'info',
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_file: './logs/combined.log',
      time: true,
      merge_logs: true,
      max_memory_restart: '500M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      health_check_grace_period: 30000,
      health_check_fatal_exceptions: true,
      autorestart: true,
      exp_backoff_restart_delay: 100,
      env_file: '.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      monitoring: false,
      pmx: false,
      watch: false,
      ignore_watch: ['node_modules', 'dist', 'logs', '.git'],
    },
  ],
};
