import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: [
      'src/lib/__tests__/openapi-contract.test.ts',
      'src/lib/__tests__/openapi-path-sync.test.ts',
      'src/lib/__tests__/openapi-error-envelope-guard.test.ts',
      'src/lib/__tests__/openapi-route-gap-baseline.test.ts',
      'src/lib/__tests__/openapi-success-schema-guard.test.ts',
      'src/lib/__tests__/openapi-social-lifecycle-contract.test.ts',
      'src/lib/__tests__/openapi-p1-collections-contract.test.ts',
      'src/lib/__tests__/openapi-p1-events-favorites-contract.test.ts',
      'src/lib/__tests__/admin-release-status-api.test.ts',
      'src/lib/__tests__/admin-provider-health-api.test.ts',
      'src/lib/__tests__/places-detail-api.test.ts',
      'src/lib/__tests__/places-photos-api.test.ts',
      'src/lib/__tests__/places-followers-api.test.ts',
      'src/lib/__tests__/places-like-api.test.ts',
      'src/lib/__tests__/places-share-api.test.ts',
      'src/lib/__tests__/places-visit-api.test.ts',
      'src/lib/__tests__/places-badges-api.test.ts',
      'src/lib/__tests__/places-analytics-api.test.ts',
      'src/lib/__tests__/places-availability-api.test.ts',
      'src/lib/__tests__/places-promotions-api.test.ts',
      'src/lib/__tests__/places-review-analytics-api.test.ts',
      'src/lib/__tests__/places-rating-distribution-api.test.ts',
      'src/lib/__tests__/places-request-verification-api.test.ts',
      'src/lib/__tests__/places-follow-api.test.ts',
      'src/lib/__tests__/places-verification-api.test.ts',
      'src/lib/__tests__/places-list-cache-api.test.ts',
      'src/lib/__tests__/social-capabilities-api.test.ts',
      'src/lib/__tests__/social-match-profile-api.test.ts',
      'src/lib/__tests__/users-suggestions-api.test.ts',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'json-summary', 'lcov'],
      include: [
        'src/pages/api/docs/openapi.json.ts',
        'src/pages/api/places/index.ts',
        'src/pages/api/places/[id]/index.ts',
        'src/pages/api/places/[id]/analytics.ts',
        'src/pages/api/places/[id]/availability.ts',
        'src/pages/api/places/[id]/badges.ts',
        'src/pages/api/places/[id]/follow.ts',
        'src/pages/api/places/[id]/followers.ts',
        'src/pages/api/places/[id]/like.ts',
        'src/pages/api/places/[id]/photos.ts',
        'src/pages/api/places/[id]/promotions.ts',
        'src/pages/api/places/[id]/rating-distribution.ts',
        'src/pages/api/places/[id]/request-verification.ts',
        'src/pages/api/places/[id]/review-analytics.ts',
        'src/pages/api/places/[id]/share.ts',
        'src/pages/api/places/[id]/verification.ts',
        'src/pages/api/places/[id]/visit.ts',
        'src/pages/api/social/capabilities.ts',
        'src/pages/api/social/match-profile.ts',
        'src/pages/api/users/suggestions.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        statements: 80,
        branches: 65,
      },
    },
  },
});
