-- Blog yazıları: Ekim 2026 – Mart 2027 (content kolonu dahil)
INSERT INTO blog_posts (title, slug, content, excerpt, content_html, category, category_slug, author_id, author_name, published_at, status, read_time_minutes, featured_image, cover_image, seo_title, seo_description, tags, is_featured, view_count)
VALUES

('Ekim''de Şanlıurfa: Sonbaharın En Güzel Gezi Mevsimi','ekimde-sanliurfa-sonbahar-gezi-rehberi',
'Yaz sıcağının dindiği Ekim, Şanlıurfa''yı keşfetmek için en ideal ay. Göbeklitepe''den Halfeti''ye, Harran''dan Balıklıgöl''e tüm güzelliklere tam erişim. Ekim''de Şanlıurfa ortalama 22–28°C ile ziyaretçiler için mükemmel bir konfor sunar. Özellikle sabah erken saatlerde Göbeklitepe''yi ziyaret etmek, hem ışık hem sıcaklık açısından yılın en keyifli deneyimini yaşatır. Ekim 2026''da gerçekleşecek Şanlıurfa Kültür ve Turizm Festivali (8–12 Ekim) şehrin en büyük kültürel etkinliğidir.',
'Yaz sıcağının dindiği Ekim, Şanlıurfa''yı keşfetmek için en ideal ay. Göbeklitepe''den Halfeti''ye, Harran''dan Balıklıgöl''e tüm güzelliklere tam erişim.',
'<h2>Ekim''de Şanlıurfa Nasıl Bir Yer?</h2><p>Şanlıurfa''da Ekim ayı ortalama 22–28°C ile ziyaretçiler için mükemmel bir konfor sunar. Yaz aylarının 45°C kavuran sıcağı geride kalır; arkeolojik alanlar, açık hava müzeleri ve tarihi çarşılar tam kapasiteyle keşfedilebilir hale gelir. Özellikle sabah erken saatlerde Göbeklitepe''yi ziyaret etmek, hem ışık hem sıcaklık açısından yılın en keyifli deneyimini yaşatır.</p><h2>Ekim''de Gezilecek 5 Yer</h2><ul><li><strong>Göbeklitepe:</strong> Sabah 08:00–10:00 arası altın ışıkla fotoğraf için ideal.</li><li><strong>Halfeti:</strong> Fırat kıyısında tekne turu, sonbahar renkleriyle zirve sezon.</li><li><strong>Harran:</strong> Konik evlerin gölgesinde sakin bir öğleden sonra turu.</li><li><strong>Balıklıgöl:</strong> Akşam saatlerinde loş ışıkta mistik atmosfer.</li><li><strong>Tarihi Çarşılar:</strong> Baharatlı kapalıçarşı ve bakırcılar, sıcak havada daha keyifli.</li></ul><h2>Ekim Etkinlikleri</h2><p>Ekim 2026''da gerçekleşecek <strong>Şanlıurfa Kültür ve Turizm Festivali</strong> (8–12 Ekim) şehrin en büyük kültürel etkinliğidir.</p><h3>SSS: Ekim''de Şanlıurfa gezisi için kaç gün yeterli?</h3><p>Şanlıurfa''yı Ekim ayında tam olarak deneyimlemek için minimum 3–4 gün önerilir: ilk gün Balıklıgöl ve tarihi merkez, ikinci gün Göbeklitepe ve Karahantepe, üçüncü gün Halfeti ve Fırat kıyısı, dördüncü gün Harran ve çevre köyler için idealdir.</p>',
'Gezi Rehberi','gezi-rehberi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-10-02 09:00:00+03','published',6,
'/uploads/places/gobeklitepe.jpg','/uploads/places/gobeklitepe.jpg',
'Ekim''de Şanlıurfa Gezi Rehberi 2026 — Sonbahar Tatili',
'Ekim 2026''da Şanlıurfa''da ne yapılır? Göbeklitepe, Halfeti, Harran için sonbahar gezi rehberi.',
ARRAY['gezi','ekim','sonbahar','turizm'],false,0),

('Şanlıurfa''da Baklava: Ustadan Usul, En İyi Adresler','sanliurfa-baklava-en-iyi-adresler',
'Şanlıurfa baklavası Gaziantep''e rakip mı? Kadayıf, şöbiyet ve fıstıklı baklava için şehrin en köklü ustalarını keşfedin. Urfa usulü baklava genellikle daha bol fıstıklı, biraz daha az tatlı ve yufkası daha kıtır olur.',
'Şanlıurfa baklavası Gaziantep''e rakip mı? Kadayıf, şöbiyet ve fıstıklı baklava için şehrin en köklü ustalarını keşfedin.',
'<h2>Şanlıurfa Baklavası Neden Farklı?</h2><p>Şanlıurfa baklavası, Gaziantep''inkinden ince yufka tekniği ve antep fıstığı oranıyla ayrılır. Urfa usulü baklava genellikle daha bol fıstıklı, biraz daha az tatlı ve yufkası daha kıtır olur.</p><h2>Mutlaka Tatmalısınız</h2><ul><li><strong>Fıstıklı Baklava:</strong> Klasik, tam kat fıstık dolgulu.</li><li><strong>Şöbiyet:</strong> Kıyılmış ceviz/fıstık + kaymak içeren rulo baklava.</li><li><strong>Kadayıf:</strong> Tel kadayıf tabanında sıcak servis, peynirli veya sade.</li></ul><h3>SSS: Şanlıurfa baklavası kaç kalori?</h3><p>Ortalama bir dilim (50g) Şanlıurfa fıstıklı baklavası yaklaşık 300–350 kalori içerir. Yüksek fıstık içeriği nedeniyle sağlıklı yağ oranı diğer tatlılara göre yüksektir. Günde 1–2 dilim keyifli bir deneyim için yeterlidir.</p>',
'Yeme İçme','yeme-icme','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-10-09 09:00:00+03','published',5,
'/uploads/places/balikligol.jpg','/uploads/places/balikligol.jpg',
'Şanlıurfa Baklava Rehberi — En İyi Baklavacılar','Şanlıurfa''da en iyi baklava nerede yenir? Fıstıklı baklava, kadayıf ve şöbiyet için rehber.',
ARRAY['baklava','tatlı','yeme-içme','gastronomi'],false,0),

('Şanlıurfa''nın En Güzel Camileri: Tarihi Şaheserler','sanliurfa-en-guzel-camileri-tarihi',
'Şanlıurfa, inanç turizmi açısından Türkiye''nin en önemli şehirlerinden biridir. Dergah Camii, Halilürrahman ve Ulu Cami. Hz. İbrahim''in doğduğu topraklar olarak kabul edilen bu kentte, ibadet mekanları aynı zamanda birer tarihi anıttır.',
'Urfa, camileriyle de tarihe meydan okur. Hz. İbrahim''e adanmış mekânlardan Osmanlı döneminin taş işçiliğine uzanan bir mimari yolculuk.',
'<h2>İnanç Turizmi ve Şanlıurfa Camileri</h2><p>Şanlıurfa, inanç turizmi açısından Türkiye''nin en önemli şehirlerinden biridir. Hz. İbrahim''in doğduğu topraklar olarak kabul edilen bu kentte, ibadet mekanları aynı zamanda birer tarihi anıttır.</p><h3>1. Dergah Camii (Mevlid-i Halil)</h3><p>Hz. İbrahim''in doğduğu mağaranın üzerine inşa edildiğine inanılan bu cami, Balıklıgöl kompleksinin kalbindedir.</p><h3>2. Halilürrahman Camii</h3><p>Balıklıgöl''ün hemen kenarında, suyla iç içe konumu ve taş mimarisiyle fotoğrafçıların gözdesi.</p><h3>SSS: Şanlıurfa''da kaç tarihi cami var?</h3><p>Şanlıurfa''da 500''den fazla cami bulunmakla birlikte tarihi değer taşıyan yaklaşık 15–20 camiden söz edilir. En önemlisi Dergah/Mevlid-i Halil kompleksidir; yılda 3–4 milyon ziyaretçi çeker.</p>',
'Kültür & Tarih','kultur-tarih','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-10-16 09:00:00+03','published',7,
'/uploads/places/balikligol.jpg','/uploads/places/balikligol.jpg',
'Şanlıurfa''nın En Güzel Camileri — Tarihi Mimari Rehberi',
'Şanlıurfa''da ziyaret edilecek tarihi camiler: Dergah, Halilürrahman, Ulu Cami. İnanç turizmi rehberi.',
ARRAY['camiler','inanç-turizmi','tarih','mimari'],false,0),

('Karahantepe Rehberi: Göbeklitepe''nin Kardeş Kazısı','karahantepe-rehberi-gobeklitepe-kardes-kazisi',
'Karahantepe, Şanlıurfa''ya 64 km uzaklıkta, Tektek Dağları eteklerinde yer alan ve M.Ö. 9.000–10.000 yıllarına tarihlendirilen Neolitik dönem arkeolojik alanıdır. 2019''dan itibaren yürütülen kazılar buranın Göbeklitepe ile eş zamanlı olduğunu ortaya koymuştur. Alan henüz %3''ü kazılmış haldedir.',
'Göbeklitepe''den 46 km uzakta, belki daha eski: Karahantepe. Taş sütunlar, insan kabartmaları ve çözülmeyi bekleyen sırlar.',
'<h2>Karahantepe Nedir?</h2><p>Karahantepe, Şanlıurfa''ya 64 km uzaklıkta, M.Ö. 9.000–10.000 yıllarına tarihlendirilen bir Neolitik dönem arkeolojik alanıdır. Alan henüz %3''ü kazılmış haldedir.</p><h2>Göbeklitepe''den Farkı</h2><p>Karahantepe''de insan yüzü kabartmaları ve T-sütunları üzerinde farklı figürler bulunmuştur.</p><h2>Nasıl Gidilir?</h2><p>Şehir merkezinden araçla yaklaşık 1,5 saat. Toplu ulaşım bulunmaz; kiralık araç veya tur servisi önerilir.</p><h3>SSS: Karahantepe Göbeklitepe''den daha mı eski?</h3><p>Bazı bulgular Karahantepe''nin M.Ö. 9.500–10.000 yıllarına ait olduğuna işaret eder. Arkeologlar her iki alanın da aynı kültürel geleneğin ürünü olduğu görüşündedir.</p>',
'Kültür & Tarih','kultur-tarih','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-10-23 09:00:00+03','published',6,
'/uploads/places/gobeklitepe.jpg','/uploads/places/gobeklitepe.jpg',
'Karahantepe Ziyaret Rehberi 2026 — Göbeklitepe''nin Kardeşi',
'Karahantepe nerede, nasıl gidilir? Göbeklitepe''nin yanı başındaki Neolitik arkeoloji alanı için tam rehber.',
ARRAY['karahantepe','arkeoloji','neolitik','gezi'],true,0),

('Şanlıurfa Pazar Rehberi: Hangi Gün, Nerede?','sanliurfa-pazar-rehberi-hangi-gun-nerede',
'Şanlıurfa semt pazarları sabah erken saatlerde can bulur. Taze sebze, meyve, baharat ve yerel ürünler için hangi güne gitmelisiniz? İsot, tahin, pekmez, el yapımı sabun bu pazarların en değerli ürünleridir.',
'Şanlıurfa''nın semt pazarları sabah erken saatlerde can bulur. Taze sebze, meyve, baharat ve yerel ürünler için hangi güne gitmelisiniz?',
'<h2>Neden Şanlıurfa Pazarlarına Gitmelisiniz?</h2><p>Şanlıurfa semt pazarları, şehrin gündelik yaşamının nabzını tutar. Baharat tezgâhları, çömlekçi ustalar ve taze Urfa biberi satıcıları özgün bir atmosfer oluşturur.</p><h2>Haftalık Pazar Takvimi</h2><ul><li><strong>Salı:</strong> Eyyübiye ilçesi</li><li><strong>Cumartesi:</strong> Haliliye büyük semt pazarı — en kapsamlı</li></ul><h3>SSS: Şanlıurfa pazarında fiyatlar nasıl?</h3><p>Şanlıurfa semt pazarlarında fiyatlar şehir merkezindeki dükkânlara göre %20–40 daha uygun olabilir. Pazarlık kültürü yaygındır. Cumartesi sabahı erken saatler hem en taze ürünler hem de en iyi fiyatlar için idealdir.</p>',
'Şehir Rehberi','sehir-rehberi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-11-05 09:00:00+03','published',5,
'/uploads/places/balikligol.jpg','/uploads/places/balikligol.jpg',
'Şanlıurfa Pazar Rehberi — Hangi Gün Nereye Gidilir?',
'Şanlıurfa''nın semt pazarları: gün, konum ve ne alınır? İsot, baharat, yerel ürünler için pazar rehberi.',
ARRAY['pazar','alışveriş','yerel','baharat'],false,0),

('Kış Günü Göbeklitepe: Sessiz, Büyülü, Kalabalıksız','kis-gunu-gobeklitepe-ziyaret-rehberi',
'Kış, Göbeklitepe''yi ziyaret etmek için en sessiz ve en otantik mevsimdir. Kasım–Şubat arası ziyaretçi sayısı yaza oranla %70–80 düşer; tünellerde tek başınıza durabildiğiniz nadir anlardır.',
'Kış, Göbeklitepe''yi ziyaret etmek için en sessiz ve en otantik mevsimdir. Kalabalık yok, fotoğraf için mükemmel ışık, serin hava.',
'<h2>Kışın Göbeklitepe''ye Gitmek Mantıklı mı?</h2><p>Kesinlikle evet. Kasım–Şubat arası Göbeklitepe ziyaretçi sayısı yaza oranla %70–80 düşer. Tünellerden geçip sütunların yanında tek başınıza durabildiğiniz, rehberle uzun uzun konuşabildiğiniz nadir anlardır.</p><h2>Kış Ziyareti İçin Pratik Bilgiler</h2><ul><li>Sıcaklık: 5–15°C; rüzgarlı olabilir, kat kat giyinin.</li><li>Açılış saati: 08:00 — ilk girenlerin sessizliğini kaçırmayın.</li></ul><h3>SSS: Kışın Göbeklitepe''ye gidilir mi?</h3><p>Evet, kışın Göbeklitepe''ye gitmek hem pratik hem deneyim açısından avantajlıdır. Alan yıl boyunca açıktır; Kasım–Şubat döneminde kalabalık minimumdur. Kar son derece nadirdir.</p>',
'Gezi Rehberi','gezi-rehberi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-11-13 09:00:00+03','published',5,
'/uploads/places/gobeklitepe.jpg','/uploads/places/gobeklitepe.jpg',
'Kışın Göbeklitepe Ziyareti 2026-2027 — Rehber ve İpuçları',
'Kışın Göbeklitepe''ye gitmek için rehber: sessiz, kalabalıksız ziyaret. Kasım-Şubat döneminde ne beklenir?',
ARRAY['göbeklitepe','kış','ziyaret','arkeoloji'],true,0),

('Şanlıurfa''da Geleneksel Kahvaltı: 7 Efsane Lezzet','sanliurfa-geleneksel-kahvalti-rehberi',
'Urfa kahvaltısı bir öğün değil, bir törendir. Çiğ köfte, kaymak, bal, peynir ve taze tandır ekmeği ile başlayan güne dair her şey. Kişi başı 150–250 TL arasında tam bir kahvaltı sofrası sunulur.',
'Urfa kahvaltısı bir öğün değil, bir törendir. Çiğ köfte, kaymak, bal, peynir ve taze tandır ekmeği ile başlayan güne dair her şey.',
'<h2>Şanlıurfa Kahvaltısı Neden Özeldir?</h2><p>Şanlıurfa kahvaltısı, Güneydoğu Anadolu mutfak geleneğinin en zengin ifadesidir. Onlarca küçük tabaktan oluşan, sabahın erken saatlerinde sunulan bir sofra şölenidir.</p><h2>Urfa Kahvaltısında Olmazsa Olmazlar</h2><ol><li><strong>Kaymak ve Bal:</strong> Köy usulü kaymak, saf çiçek balı, taze tandır ekmeği.</li><li><strong>Mırra:</strong> Acı, koyu Urfa kahvesi.</li><li><strong>İsotlu Menemen:</strong> Taze isot biberle yapılır.</li><li><strong>Taze Tandır Ekmeği:</strong> Sabah 06:00–08:00 arası fırından çıkar.</li></ol><h3>SSS: Şanlıurfa kahvaltısı ne kadar sürer ve kaça mal olur?</h3><p>Şanlıurfa''da geleneksel kahvaltı genellikle 1–2 saat süren sosyal bir etkinliktir. Kişi başı 150–250 TL arasında tam bir kahvaltı sofrası sunulur. Sabah erken (07:00–09:00) gidilmesi hem taze ekmeği hem en az kalabalığı yakalamak için idealdir.</p>',
'Yeme İçme','yeme-icme','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-11-20 09:00:00+03','published',5,
'/uploads/places/balikligol.jpg','/uploads/places/balikligol.jpg',
'Şanlıurfa Geleneksel Kahvaltı Rehberi — En İyi Lezzetler',
'Şanlıurfa kahvaltısı nelerden oluşur? Kaymak, mırra, kavut ve isot ile dolu geleneksel kahvaltı rehberi.',
ARRAY['kahvaltı','yeme-içme','gastronomi','urfa'],false,0),

('Şanlıurfa 2 Günlük Kış Gezi Planı','sanliurfa-2-gunluk-kis-gezi-plani',
'Kış tatilinde Şanlıurfa''ya sadece 2 gününüz mü var? Göbeklitepe, Harran, Balıklıgöl ve ciğer kebabını atlamamak için tam plan.',
'Kış tatilinde Şanlıurfa''ya sadece 2 gününüz mü var? Bu plana bakın: Göbeklitepe, Harran, Balıklıgöl ve en lezzetli durak.',
'<h2>Gün 1: Tarihi Merkez ve Göbeklitepe</h2><p>Sabah 08:00''de Göbeklitepe. Kış aylarında kalabalık yok. Öğle Balıklıgöl''de ciğer kebabı. Öğleden sonra tarihi çarşı turu.</p><h2>Gün 2: Harran ve Halfeti</h2><p>Sabah Harran: konik evler, tarihi üniversite kalıntıları. Öğleden sonra Halfeti''de Fırat manzarası.</p><h3>SSS: 2 günlük Şanlıurfa gezisinde neleri atlamamalıyım?</h3><p>2 günlük Şanlıurfa gezisinde mutlaka: Göbeklitepe (sabah erken), Balıklıgöl kompleksi, Harran konik evleri ve bir kez de olsa ciğer kebabı yenilmesi gerekir. Tarihi çarşıdan isot almadan gitmeyin.</p>',
'Gezi Rehberi','gezi-rehberi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-12-03 09:00:00+03','published',6,
'/uploads/places/harran.jpg','/uploads/places/harran.jpg',
'Şanlıurfa 2 Günlük Kış Gezi Planı — Göbeklitepe ve Harran',
'Şanlıurfa''ya 2 günlük kış gezisi planı. Göbeklitepe, Harran, Halfeti ve tarihi çarşı turu.',
ARRAY['gezi-planı','kış','2-gün','itinerary'],false,0),

('Şanlıurfa''nın Geleneksel İçecekleri: Mırradan Şalgama','sanliurfa-geleneksel-icecekler-mirra-salgam',
'Şanlıurfa''da ne içilir? Acı mırra kahvesinden ekşili şalgama, boza''dan tamarind şerbetine. Mırra küçük bardaklarda sıcak olarak içilir; fincanı ters çevirmek isteksizliği belirtir.',
'Şanlıurfa''da ne içilir? Acı mırra kahvesinden ekşili şalgama, boza''dan tamarind şerbetine. Yerel içki kültürünün tam rehberi.',
'<h2>Mırra: Urfa''nın Acı Ritüeli</h2><p>Mırra, küçük kulpsuz fincanlarda (bardak) sunulan, koyu ve acı kahvedir. Misafire mırra ikram etmek güçlü bir saygı işaretidir.</p><h2>Şalgam Suyu</h2><p>Kırmızı renkli, ekşili, acı biberli şalgam Güneydoğu''nun vazgeçilmez içeceğidir.</p><h3>SSS: Mırra nasıl içilir, ne kadar içilir?</h3><p>Mırra küçük bardaklarda sıcak olarak içilir. Tek seferde 1–3 bardak normaldir; fincanı ters çevirmek içmek istemediğinizi belirtir. Akşam saatlerinde içmek uyku sorunlarına yol açabilir; öğleden önce tatmak daha sağlıklıdır.</p>',
'Yeme İçme','yeme-icme','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-12-10 09:00:00+03','published',5,
'/uploads/places/balikligol.jpg','/uploads/places/balikligol.jpg',
'Şanlıurfa Geleneksel İçecekler — Mırra, Şalgam, Şerbet Rehberi',
'Şanlıurfa''da ne içilir? Mırra kahvesi, şalgam, hoşaf ve boza hakkında tam içecek rehberi.',
ARRAY['mırra','içecek','gastronomi','kültür'],false,0),

('Urfa İsotu: Dünyanın En Aromatik Biberi','urfa-isotu-dunya-en-aromatik-biber',
'İsot — kuru Urfa biberi — dünya mutfaklarına girmeye başlayan Şanlıurfa''nın lezzet elçisi. Scoville ölçeğinde 30.000–50.000 birim; duman, çikolata ve meşe notaları. Nasıl yetiştirilir, nasıl kullanılır?',
'İsot — kuru Urfa biberi — dünya mutfaklarına girmeye başlayan Şanlıurfa''nın lezzet elçisi. Nasıl yetiştirilir, nasıl kurutulur, nasıl kullanılır?',
'<h2>İsot Nedir?</h2><p>İsot, Şanlıurfa''ya özgü kırmızı biberden gece-gündüz sıcaklık farkıyla fermente edilerek hazırlanan aromatik bir baharattır. Duman, çikolata ve meşe notaları taşır.</p><h2>Nasıl Kullanılır?</h2><ul><li>Urfa kebabının olmazsa olmazı</li><li>Yumurta, omlet, menemen üzerine</li><li>Çorba ve mercimek yemeklerinde</li></ul><h3>SSS: Urfa isotu ne kadar acı, nasıl saklanır?</h3><p>Urfa isotu Scoville ölçeğinde 30.000–50.000 birim aralığındadır; jalapeño''dan daha acı ama habanero''dan daha az. Kapalı cam kavanozda, ışıktan uzakta tutulması yeterlidir; buzdolabında 12 aya kadar aroma korur.</p>',
'Gastronomi','gastronomi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2026-12-18 09:00:00+03','published',6,
'/uploads/places/balikligol.jpg','/uploads/places/balikligol.jpg',
'Urfa İsotu Rehberi — Dünyanın En Aromatik Biberi',
'Urfa isotu nedir, nasıl yapılır, nasıl kullanılır? İsot''un hikayesi, üretimi ve alışveriş rehberi.',
ARRAY['isot','baharat','gastronomi','urfa'],true,0),

('Yeni Yılda Şanlıurfa: Kış Tatili İçin 10 Neden','yeni-yilda-sanliurfa-kis-tatili-10-neden',
'Ocak ayında Şanlıurfa''ya gitmek için 10 sağlam neden: boş tarihi alanlar, uygun fiyatlar, yerel kültür. Göbeklitepe''de tek başınıza durabilirsiniz; oteller %30–50 indirimlidir.',
'Ocak ayında Şanlıurfa''ya gitmek için 10 sağlam neden: boş tarihi alanlar, uygun fiyatlar, yerel festivaller.',
'<h2>Ocak''ta Şanlıurfa Neden İdeal?</h2><p>Yılın ilk ayları Şanlıurfa turizminin en sessiz dönemidir; her yer açık, her yer boş, fiyatlar en uygun seviyede.</p><h2>10 Neden</h2><ol><li>Göbeklitepe''de tek başınıza durabilirsiniz.</li><li>Oteller %30–50 indirimli.</li><li>Uçak biletleri yılın en düşük seviyesinde.</li><li>Tarihi çarşıda esnafla gerçek sohbet şansı.</li><li>Akşam Balıklıgöl''ün ışık oyunları kalabalıksız izlenir.</li></ol><h3>SSS: Ocak ayında Şanlıurfa hava durumu nasıl?</h3><p>Şanlıurfa''da Ocak ortalama sıcaklığı 5–10°C arasındadır. Kar yağışı nadir görülür (yılda 1–3 gün). Rüzgar keskin olabilir; kalın mont ve su geçirmez ayakkabı önerilir.</p>',
'Gezi Rehberi','gezi-rehberi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2027-01-07 09:00:00+03','published',5,
'/uploads/places/harran.jpg','/uploads/places/harran.jpg',
'Ocak''ta Şanlıurfa Kış Tatili — 10 Neden ve Rehber',
'Yeni yılda Şanlıurfa''ya gitmek için 10 neden. Kış tatilinde uygun fiyat, boş tarihi alan ve otantik deneyim.',
ARRAY['ocak','kış-tatili','turizm','gezi'],false,0),

('Halfeti Balıkçılığı ve Fırat Mutfağı','halfeti-balikcilik-firat-mutfagi',
'Halfeti''nin Fırat kıyısındaki restoranlarında sazan, levrek ve yayın balığıyla zenginleşen yöresel mutfak. Balık lezzeti açısından Ekim–Mart dönemi idealdir.',
'Halfeti''nin Fırat kıyısındaki restoranlarında sazan, levrek ve yayın balığıyla zenginleşen yöresel mutfak.',
'<h2>Fırat''ın Balıkları</h2><p>Halfeti''de Fırat Nehri, sazan, yayın, levrek ve kaya balığı barındırır. Yöre halkı balıkçılığı hem geçim kaynağı hem hobi olarak sürdürür.</p><h2>Halfeti Mutfağında Balık</h2><ul><li><strong>Izgara Sazan:</strong> Taze sazan, közlenmiş biber ve soğanla servis edilir.</li><li><strong>Balık Çorbası:</strong> Tatlı su balıklarından, maydanoz ve limonla.</li></ul><h3>SSS: Halfeti''de balık restoranları ne zaman açık?</h3><p>Halfeti''deki balık restoranlarının büyük çoğunluğu yıl boyunca açıktır. Hafta sonları daha garantili bir deneyim için önceden arama yapmanızı öneririz.</p>',
'Gastronomi','gastronomi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2027-01-22 09:00:00+03','published',5,
'/uploads/places/halfeti.jpg','/uploads/places/halfeti.jpg',
'Halfeti Balıkçılık ve Fırat Mutfağı — Yöresel Balık Rehberi',
'Halfeti''de ne yenir? Fırat balıkları, sazan, yayın ve yöresel balık mutfağı için tam rehber.',
ARRAY['halfeti','balık','gastronomi','fırat'],false,0),

('Şanlıurfa Müzeleri: Hangi Müze, Ne Zaman?','sanliurfa-muzeleri-hangi-muze-ne-zaman',
'Arkeoloji Müzesi''nden Mozaik Müzesi''ne, Haleplibahçe''den Göbeklitepe ziyaretçi merkezine. Şanlıurfa''nın müze haritası. Pazartesi günleri kapalıdır.',
'Arkeoloji Müzesi''nden Mozaik Müzesi''ne, Haleplibahçe''den Göbeklitepe ziyaretçi merkezine. Şanlıurfa''nın müze haritası.',
'<h2>Şanlıurfa Müze Haritası</h2><p>Şanlıurfa, Türkiye''nin en zengin arkeolojik müzelerinden bazılarına ev sahipliği yapar.</p><h3>1. Şanlıurfa Arkeoloji Müzesi</h3><p>Urfa Adamı (M.Ö. 9.000) heykeli, Neolitik dönem buluntuları. Ziyaret süresi: 2–3 saat. Pazartesi kapalı.</p><h3>2. Haleplibahçe Mozaik Müzesi</h3><p>Dünyanın en büyük in-situ mozaik koruma alanlarından biri.</p><h3>SSS: Şanlıurfa Arkeoloji Müzesi giriş ücreti ne kadar, ne zaman açık?</h3><p>Güncel giriş ücreti için resmi Kültür Bakanlığı web sitesini kontrol edin. Genel açılış saatleri 08:00–17:00 (kış) ve 08:00–19:00 (yaz). Pazartesi kapalıdır; Müze Kart sahipleri ücretsiz giriş yapabilir.</p>',
'Kültür & Tarih','kultur-tarih','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2027-02-05 09:00:00+03','published',6,
'/uploads/places/balikligol.jpg','/uploads/places/balikligol.jpg',
'Şanlıurfa Müzeleri Rehberi 2027 — Hangi Müze, Ne Zaman?',
'Şanlıurfa''da hangi müzeler var? Arkeoloji Müzesi, Mozaik Müzesi, Göbeklitepe. Ziyaret saatleri ve bilet rehberi.',
ARRAY['müze','arkeoloji','kültür','tarih'],false,0),

('Şanlıurfa''da Romantik Mekanlar: Çiftler İçin Rehber','sanliurfa-romantik-mekanlar-sevgililer-rehberi',
'Şanlıurfa, romantizm için beklenmedik bir şehir. Halfeti''nin batık köyü, Balıklıgöl''ün akşam ışıkları ve yıldızlı Harran gökyüzü çiftler için eşsizdir.',
'Şanlıurfa, romantizm için beklenmedik bir şehir olabilir. Halfeti''nin batık köyü, Balıklıgöl''ün akşam ışıkları ve yıldızlı Harran gökyüzü.',
'<h2>Şanlıurfa''nın Romantik Yüzü</h2><p>Halfeti''de Fırat''ta tekne sürmek ya da Harran''ın açık gökyüzünde yıldızları izlemek; çift seyahatleri için eşsiz anlar yaratır.</p><h2>En Romantik 5 Deneyim</h2><ol><li>Halfeti''de Gün Batımı Tekne Turu</li><li>Balıklıgöl Gece Yürüyüşü</li><li>Harran''da Yıldız Gözlemi</li><li>Tarihi Taş Otel Kahvaltısı</li><li>Baharatlı çarşıda el ele dolaşmak</li></ol><h3>SSS: Şanlıurfa çiftler için uygun bir tatil yeri mi?</h3><p>Evet, Şanlıurfa çiftler için mükemmel bir tatil destinasyonudur. Halfeti''nin pitoresk manzarası ve tarihi taş otellerin romantik konforunu düşündüğünüzde bu şehir güzel bir çift seyahati için her türlü unsuru barındırır. Bahar (Nisan-Mayıs) ve Sonbahar (Eylül-Ekim) en uygun mevsimlerdir.</p>',
'Gezi Rehberi','gezi-rehberi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2027-02-13 09:00:00+03','published',5,
'/uploads/places/halfeti.jpg','/uploads/places/halfeti.jpg',
'Şanlıurfa Romantik Mekanlar — Çiftler İçin Rehber',
'Şanlıurfa''da romantik ne yapılır? Halfeti tekne turu, Balıklıgöl gece yürüyüşü ve yıldızlı Harran.',
ARRAY['romantik','çift','halfeti','balıklıgöl'],false,0),

('Şanlıurfa''da İlkbahar: Mart–Mayıs Gezi Rehberi','sanliurfa-ilkbahar-mart-mayis-gezi-rehberi',
'İlkbahar Şanlıurfa''nın en güzel halidir. Kırlarda çiçekler, Halfeti''de siyah güller Nisan ortasında tam çiçekte ve Göbeklitepe''de altın ışık — nisan ve mayısı kaçırmayın.',
'İlkbahar Şanlıurfa''nın en güzel halidir. Kırlarda çiçekler, Halfeti''de siyah güller ve Göbeklitepe''de altın ışık — nisan ve mayısı kaçırmayın.',
'<h2>Neden İlkbahar?</h2><p>Mart sonu itibarıyla sıcaklıklar 15–22°C''ye ulaşır; kırlar yeşillenir, Halfeti''de nadir siyah güller çiçek açar.</p><h2>İlkbaharda Şanlıurfa Takvimi</h2><h3>Nisan</h3><p>Halfeti''de siyah güllerin en yoğun çiçeklenme dönemi. Nisan ortasında güller tam çiçektedir.</p><h3>Mayıs</h3><p>Şanlıurfa Festivaller Ayı: turizm etkinlikleri, sıra gecesi şölenleri.</p><h3>SSS: Halfeti''de siyah güller ne zaman çiçek açar?</h3><p>Halfeti''nin ünlü siyah gülleri genellikle <strong>Nisan ortasından Mayıs başına</strong> kadar en güzel çiçeklenme dönemini yaşar. Tekne turu sırasında kıyı kayalıklarında en iyi görüntülenir.</p>',
'Gezi Rehberi','gezi-rehberi','7a2816aa-d85a-481e-aa41-c89380f47d8f','Şanlıurfa Editörü','2027-03-06 09:00:00+03','published',6,
'/uploads/places/halfeti.jpg','/uploads/places/halfeti.jpg',
'Şanlıurfa İlkbahar Rehberi — Mart Nisan Mayıs Gezi Planı',
'İlkbaharda Şanlıurfa: Halfeti siyah gülleri, Göbeklitepe ve Nevruz. Mart-Mayıs döneminde ne yapılır?',
ARRAY['ilkbahar','mart','nisan','halfeti','siyah-güller'],true,0)
;
