-- Q4 2026 / Q1 2027 Etkinlikleri + Karahantepe Mekan

-- 1. Karahantepe mekan ekle (category_id=225 = Tarihi yerler)
INSERT INTO places (
  id, name, slug, description, short_description, meta_description,
  category, category_id, address, latitude, longitude,
  phone, status, image_url, thumbnail_url,
  avg_rating, review_count, rating_count, is_featured, is_verified,
  view_count, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  'Karahantepe Arkeoloji Alanı',
  'karahantepe-arkeoloji-alani',
  'Karahantepe, Şanlıurfa''ya 64 km uzaklıkta, Tektek Dağları eteklerinde yer alan Neolitik dönem arkeoloji alanıdır. M.Ö. 9.000–10.000 yıllarına tarihlendirilen alan, 2019''dan itibaren yürütülen kazılarla Göbeklitepe ile eş zamanlı bir uygarlığın izlerini ortaya koymaktadır. T-sütunları, insan yüzü kabartmaları ve benzersiz arkeolojik bulgularıyla dikkat çeken Karahantepe, henüz yüzde 3''ü kazılmış haldedir.',
  'Göbeklitepe''nin kardeşi: M.Ö. 9.000–10.000 yıllarına ait Neolitik arkeoloji alanı. T-sütunları ve insan yüzü kabartmaları.',
  'Karahantepe Şanlıurfa''ya 64 km uzaklıkta Neolitik dönem arkeoloji alanı. Göbeklitepe ile eş zamanlı uygarlık kalıntıları, ziyaret rehberi.',
  'turizm',
  225,
  'Tektek Dağları, Karaharabe Köyü, Viranşehir, Şanlıurfa',
  37.1456,
  39.0223,
  NULL,
  'active',
  '/uploads/places/gobeklitepe.jpg',
  '/uploads/places/gobeklitepe.jpg',
  4.8,
  0,
  0,
  true,
  true,
  0,
  NOW(),
  NOW()
) ON CONFLICT (slug) DO NOTHING;

-- 2. Ocak 2027 Etkinlikleri
INSERT INTO events (id, title, slug, description, start_date, end_date, location, organizer, category, status, is_free, is_online, image_url, view_count, created_at, updated_at)
VALUES

(gen_random_uuid(),
'Karahantepe Kış Arkeoloji Turu 2027',
'karahantepe-kis-arkeoloji-turu-2027',
'Göbeklitepe''nin kardeşi Karahantepe''yi keşfetmek için kış dönemi rehberli tur. Arkeologların eşliğinde kazı alanı gezisi, M.Ö. 9.000''e ait buluntular hakkında sunum. Kış mevsiminde kalabalıksız, samimi bir arkeoloji deneyimi.',
'2027-01-10 08:30:00', '2027-01-10 17:00:00',
'Karahantepe Arkeoloji Alanı, Viranşehir',
'Şanlıurfa Arkeoloji Derneği',
'Turizm', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Urfa Müzeler Haftası — Özel Gece Gezileri',
'urfa-muzeler-haftasi-gece-gezileri-2027',
'Şanlıurfa Arkeoloji Müzesi ve Haleplibahçe Mozaik Müzesi''nde özel gece sergileri ve rehberli turlar. Müze kapandıktan sonra loş ışıkta mozaikleri keşfetme fırsatı. Kişi başı sınırlı kontenjan.',
'2027-01-16 18:00:00', '2027-01-16 22:00:00',
'Şanlıurfa Arkeoloji Müzesi',
'Şanlıurfa Valiliği Kültür İşleri',
'Kültür', 'published', false, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Ocak Gastronomi Atölyesi: Urfa Mutfağının Sırları',
'ocak-gastronomi-atolyesi-urfa-mutfagi-2027',
'İsot kurutma, mırra demleme ve Urfa kebabının püf noktaları. Şanlıurfa''nın usta aşçılarından 3 saatlik interaktif mutfak atölyesi. Katılımcılar yaptıklarını eve götürür.',
'2027-01-18 10:00:00', '2027-01-18 13:00:00',
'Şanlıurfa Gastronomi Merkezi',
'Urfa Mutfağı Derneği',
'Gastronomi', 'published', false, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Halfeti Kış Balıkçılık Turu',
'halfeti-kis-balikcilik-turu-2027',
'Halfeti''de Fırat kıyısında yerel balıkçılarla sabah erken deneyim. Sazan, yayın ve levrek avı. Turun ardından fırın balığı ile öğle yemeği. Kış mevsiminde Fırat''ın büyüsünü keşfet.',
'2027-01-25 06:30:00', '2027-01-25 14:00:00',
'Halfeti, Fırat Nehri Kıyısı',
'Halfeti Turizm Kooperatifi',
'Turizm', 'published', false, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

-- 3. Şubat 2027 Etkinlikleri
(gen_random_uuid(),
'Sevgililer Günü: Halfeti''de Gün Batımı Tekne Turu',
'sevgililer-gunu-halfeti-tekne-turu-2027',
'14 Şubat''a özel Halfeti''de romantik gün batımı tekne turu. Fırat''ta çift rotası, mum ışığında akşam yemeği ve yerel müzik. Erken kayıt zorunlu, kontenjan 20 çift.',
'2027-02-14 16:00:00', '2027-02-14 21:00:00',
'Halfeti, Fırat Nehri',
'Halfeti Turizm Kooperatifi',
'Festival', 'published', false, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Şanlıurfa Arkeoloji Konferansı 2027',
'sanliurfa-arkeoloji-konferansi-2027',
'Göbeklitepe ve Karahantepe araştırmacılarından güncel bulgular. Uluslararası akademisyenler ve yerli arkeologların katılımıyla iki günlük konferans. Halka açık oturumlar da mevcut.',
'2027-02-19 09:00:00', '2027-02-20 17:00:00',
'Harran Üniversitesi Kültür Merkezi',
'Harran Üniversitesi',
'Akademi', 'published', true, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Urfa El Sanatları Festivali — Kış Sergisi',
'urfa-el-sanatlari-festivali-kis-2027',
'Bakır işçiliği, kilim dokuma, sedefçilik ve çömlek ustaları ile buluşma. Canlı demo, atölye ve yöresel ürün satışı. Şehrin tarihi çarşı bölgesinde üç gün.',
'2027-02-22 10:00:00', '2027-02-24 18:00:00',
'Şanlıurfa Tarihi Kapalı Çarşı',
'Şanlıurfa Ticaret Odası',
'Kültür', 'published', true, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

-- 4. Mart 2027 Etkinlikleri
(gen_random_uuid(),
'Nevruz Kutlamaları 2027 — Göbeklitepe''de Bahar',
'nevruz-kutlamalari-gobeklitepe-2027',
'21 Mart Nevruz''unda Göbeklitepe ziyareti ve açık hava kutlaması. Ateş yakma, yöresel müzik, halk oyunları. Şanlıurfa''nın en büyük geleneksel bahar şenliği.',
'2027-03-21 10:00:00', '2027-03-21 20:00:00',
'Göbeklitepe Arkeoloji Alanı',
'Şanlıurfa Valiliği',
'Festival', 'published', true, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Halfeti Siyah Gül Sezonu Açılışı',
'halfeti-siyah-gul-sezonu-acilisi-2027',
'Halfeti''nin dünyaca ünlü siyah güllerinin ilk açılışını kutlayan bahar festivali. Tekne turları, çiçek sergisi, yerel lezzetler ve fotoğraf turu. Nisan''a uzanan sezonun başlangıç etkinliği.',
'2027-03-28 09:00:00', '2027-03-28 18:00:00',
'Halfeti İlçesi',
'Halfeti Belediyesi',
'Festival', 'published', true, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Bahar Göbeklitepe Fotoğraf Turu',
'bahar-gobeklitepe-fotograf-turu-2027',
'Profesyonel fotoğrafçılar eşliğinde sabah altın saati Göbeklitepe turu. Kompozisyon teknikleri, ışık kullanımı ve arkeoloji alanında fotoğraf. Maksimum 12 katılımcı.',
'2027-03-15 06:30:00', '2027-03-15 11:00:00',
'Göbeklitepe Arkeoloji Alanı',
'Urfa Fotoğraf Derneği',
'Sanat', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW());
