-- Q4 2027 Etkinlikleri — 10 etkinlik (Ekim–Aralık)

INSERT INTO events (id, title, slug, description, start_date, end_date, location, organizer, category, status, is_free, is_online, image_url, view_count, created_at, updated_at)
VALUES

(gen_random_uuid(),
'Şanlıurfa Sonbahar El Sanatları ve Hediyelik Fuarı 2027',
'sanliurfa-sonbahar-el-sanatlari-fuari-2027',
'Şanlıurfa''nın geleneksel el sanatları ustalarının katıldığı yıllık sonbahar fuarı. Bakırcılar, hasırcılar, dokumacılar ve takı ustaları tek çatı altında. Atölye demoları, fiyatlı ve ücretsiz kurslar. Tur operatörleri için B2B tanıtım gününü de kapsıyor. Kapalı Çarşı ve Bedesten''de üç günlük etkinlik.',
'2027-10-08 09:00:00', '2027-10-10 19:00:00',
'Kapalı Çarşı ve Bedesten, Şanlıurfa',
'Şanlıurfa Esnaf ve Zanaatkarlar Odası',
'Kültür', 'published', true, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Halfeti Sonbahar Tekne Turu Sezonu Kapanış Etkinliği 2027',
'halfeti-sonbahar-tekne-turu-sezon-kapanis-2027',
'Halfeti tekne turlarının 2027 sezonunu kapayan veda etkinliği. Son sezon turlarında yerel müzik eşliği, Fırat kıyısında taze balık ikramı ve bir sonraki sezon için erken kayıt imkânı. Balıkçılar ve tekne sahipleriyle buluşma. Siyah gül sezonundan balık mevsimine kadar geçen yılın fotoğraf sergisi.',
'2027-10-19 09:00:00', '2027-10-19 18:00:00',
'Halfeti İskelesi ve Fırat Kıyısı, Halfeti',
'Halfeti Turizm Kooperatifi',
'Turizm', 'published', false, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Şanlıurfa Uluslararası Film ve Belgesel Festivali 2027',
'sanliurfa-film-belgesel-festivali-2027',
'Şanlıurfa''nın arkeoloji, kültür ve insanını konu alan belgeseller ile kısa filmlerin gösterildiği iki günlük film festivali. Türkiye ve uluslararası arkeoloji belgecilerinin katılımı. Göbeklitepe ve Karahantepe üzerine yeni yapımların dünya prömiyeri. Harran Üniversitesi''nde salonlar halka açık.',
'2027-10-23 10:00:00', '2027-10-24 20:00:00',
'Harran Üniversitesi Sinema Salonu, Şanlıurfa',
'Harran Üniversitesi İletişim Fakültesi',
'Sanat', 'published', true, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Harran Üniversitesi Arma Anma Töreni: İlk Üniversitenin Mirası',
'harran-ilk-universite-anma-toreni-2027',
'MÖ 600''lü yıllara dayandığı kabul edilen dünyanın ilk yükseköğretim kurumunun anma töreni. Uluslararası akademisyenlerin katıldığı panel; Harran''ın bilim tarihindeki rolü, astronomi mirası ve günümüz üniversite bağlantısı üzerine. Ardından Harran''da rehberli tur. Halka açık oturumlar akşam.',
'2027-11-05 09:00:00', '2027-11-05 17:00:00',
'Harran Üniversitesi Konferans Salonu ve Harran Antik Kenti',
'Harran Üniversitesi Rektörlüğü',
'Akademi', 'published', true, false,
'/uploads/places/harran.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Kasım Urfa Mutfağı Atölyesi: Kış Yemekleri Serisi',
'kasim-urfa-mutfagi-atolyesi-kis-yemekleri-2027',
'Urfa''nın kış sofrasına özel interaktif mutfak atölyesi serisi. Beyran çorbası yapımı, kaburga dolması hazırlanması ve borani tarifi. Katılımcılar ustalarla birlikte pişiriyor ve yiyor. Her hafta sonu Kasım boyunca tekrarlanan program. Konaklama dahil paket seçeneği mevcut.',
'2027-11-07 10:00:00', '2027-11-29 13:00:00',
'Şanlıurfa Gastronomi Merkezi',
'Urfa Mutfağı Derneği',
'Gastronomi', 'published', false, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Göbeklitepe Kış Dönemi Özel Rehberli Tur 2027',
'gobeklitepe-kis-donemi-ozel-rehberli-tur-2027',
'Göbeklitepe''de kış mevsiminin ayrıcalıklı sakinliğini yaşayan özel grup turları. Aralık-Şubat döneminde günde en fazla 20 kişilik gruplara ayrılmış sabah ve öğleden sonra seansları. Arkeolog eşliğinde T-sütunlar, hayvan kabartmaları ve en yeni kazı alanları açıklaması. Öğleden sonra Karahantepe geçiş rotası seçeneği mevcut.',
'2027-11-15 08:00:00', '2027-12-31 17:00:00',
'Göbeklitepe Arkeoloji Parkı',
'Göbeklitepe Ziyaretçi Merkezi',
'Turizm', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Şanlıurfa Fotoğrafçılık Yarışması 2027 Ödül Töreni',
'sanliurfa-fotografcilik-yarismasi-odul-toreni-2027',
'Şanlıurfa.com ve Şanlıurfa Fotoğrafçılar Derneği iş birliğiyle düzenlenen yıllık fotoğrafçılık yarışmasının 2027 ödül töreni. Göbeklitepe, Halfeti ve şehir yaşamı kategorilerinde 30 finalist sergi. Ödül töreni ve galeri açılışı. Türkiye''nin dört bir yanından katılan fotoğrafçıların eserleri.',
'2027-11-21 17:00:00', '2027-11-21 21:00:00',
'Şanlıurfa Kültür ve Kongre Merkezi',
'Şanlıurfa Fotoğrafçılar Derneği',
'Sanat', 'published', false, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Harran Astronomi Gecesi 2027: Kış Gökyüzü Gözlemi',
'harran-astronomi-gecesi-kis-gokyuzu-2027',
'Harran''ın tarihsel astronomi geleneğine saygı gösteren yıllık kış gözlemi etkinliği. Güneş en kısa gün dönümüne yaklaştığında Harran Ovası''nda ışık kirliliğinden uzak gece gökyüzü izleniyor. Teleskop istasyonları, arkeoloji astronomi ilişkisi üzerine konuşma ve mırra ikramı. Harran''da geceleme için butik konaklama paketleri mevcuttur.',
'2027-12-18 18:00:00', '2027-12-19 01:00:00',
'Harran Kümbet Evleri çevresi ve Harran Ovası',
'Harran Kaymakamlığı & Astronomi Derneği',
'Kültür', 'published', false, false,
'/uploads/places/harran.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Kapalı Çarşı Kış Hediyelik Pazarı 2027',
'kapali-carsi-kis-hediyelik-pazari-2027',
'Şanlıurfa Kapalı Çarşısı''nda Aralık boyunca yılbaşı ve kış hediyelerine özel özel pazar. İsot, tahin, pekmez, bakır ve geleneksel el işlemesi ürünlerde sezon indirimleri. Zanaatkarlar hediyelik ambalaj sunuyor, kargo hizmeti var. Akşam saatlerinde özel aydınlatma ile tarihi çarşı ayrı bir atmosfer kazanıyor.',
'2027-12-15 10:00:00', '2027-12-28 20:00:00',
'Kapalı Çarşı ve Bedesten, Şanlıurfa',
'Şanlıurfa Esnaf ve Zanaatkarlar Odası',
'Kültür', 'published', true, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Yılbaşı Öncesi Halfeti Özel Gece Turu 2027',
'yilbasi-oncesi-halfeti-gece-turu-2027',
'Yılbaşına özel Halfeti''de Fırat üzerinde gece fener turu. Tekneler fenerlerle donatılarak kıyı boyunca yavaş yol alıyor. Tur sonrası kıyı restoranında balık yemeği ve yılbaşı karşılama. Sınırlı kontenjan (20 kişi); aile ve çiftlere özel paket. Halfeti''de geceleme seçeneği mevcut.',
'2027-12-30 19:00:00', '2027-12-31 01:00:00',
'Halfeti İskelesi ve Fırat Nehri, Halfeti',
'Halfeti Turizm Kooperatifi',
'Festival', 'published', false, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW())

ON CONFLICT (slug) DO NOTHING;

SELECT COUNT(*) AS etkinlik_toplam FROM events WHERE status='published';
SELECT MAX(start_date)::date AS son_etkinlik FROM events WHERE status='published';
