-- 24 Yeni Urfa/Güneydoğu Tarifi — toplam 16→40

INSERT INTO recipes (id, slug, name, description, ingredients, instructions, cover_image, prep_time, cook_time, servings, difficulty, is_spicy, is_vegetarian, is_featured, rating, view_count, status, meta_title, meta_description, created_at, updated_at)
VALUES

(gen_random_uuid(), 'beyran-corbasi', 'Beyran Çorbası',
 'Şanlıurfa''nın sabahları vazgeçilmez çorbası. Kuzu eti, pirinç ve sade et suyu ile hazırlanan, üzerine kırmızı biber yağı gezdirilen bu çorba, şehre özgü güçlü bir sabah geleneğinin sembolüdür.',
 '{"500g kuzu but eti (kemikli)","1 su bardağı pirinç","2 lt su","1 baş sarımsak","2 yemek kaşığı tereyağı","2 çay kaşığı pul biber","1 çay kaşığı karabiber","Tuz"}',
 '{"Kuzu etini bol su ile 1.5-2 saat haşlayın, kemiklerden ayırıp ince ince çekin.","Et suyunu süzün, pirinci ekleyip 15 dakika pişirin.","Kıymık hâle getirilen eti tekrar suya ekleyin, tuz ve karabiberle tadını ayarlayın.","Tereyağında pul biberi kavurun, çorbanın üzerine gezdirerek servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 20, 120, 4, 'Orta', true, false, true, 4.9, 0, 'published',
 'Beyran Çorbası Tarifi — Şanlıurfa''nın Sabah Geleneği',
 'Şanlıurfa''ya özgü sabah çorbası beyran nasıl yapılır? Kuzu eti, pirinç ve kırmızı biber yağıyla hazırlanan orijinal tarif.',
 NOW(), NOW()),

(gen_random_uuid(), 'kuru-kofte', 'Kuru Köfte',
 'Şanlıurfa usulü kuru köfte, çiğ köftenin pişmiş hâlidir. Bulgur, kıyma ve baharatların yoğrulup şekillendirilerek közde ya da tavada pişirilmesiyle hazırlanır.',
 '{"300g ince bulgur","300g az yağlı dana kıyma","1 adet yumurta","2 baş kuru soğan","3 diş sarımsak","1 demet maydanoz","1 çay kaşığı kimyon","1 çay kaşığı pul biber","Tuz, karabiber","Kızartmak için yağ"}',
 '{"Bulguru ılık suyla ıslatıp 20 dakika bekletin.","Kıymayı soğan, sarımsak ve baharatlarla iyice yoğurun.","Yumuşayan bulguru kıyma karışımına ekleyin, maydanoz ekleyip tekrar yoğurun.","Ceviz büyüklüğünde yuvarlak şekil verin.","Yağlı tavada veya közde her iki yüzünü kızartın."}',
 '/images/hero/sanliurfa-editorial-food.webp', 30, 20, 6, 'Kolay', true, false, false, 4.6, 0, 'published',
 'Kuru Köfte Tarifi — Şanlıurfa Usulü',
 'Şanlıurfa''nın pişmiş köftesi olan kuru köfte tarifi. Bulgur ve kıymanın birleşimiyle hazırlanan geleneksel lezzet.',
 NOW(), NOW()),

(gen_random_uuid(), 'tahin-pekmez', 'Tahin Pekmez',
 'Şanlıurfa kahvaltı sofralarının olmazsa olmazı. Üzüm pekmezi ve susam tahininin birlikte sunulduğu bu basit ama derin lezzet, bölgenin tarımsal zenginliğini yansıtır.',
 '{"200g koyu üzüm pekmezi","200g saf susam tahin","Yanında sıcak lavaş veya köy ekmeği"}',
 '{"Tahin ve pekmezi ayrı ayrı küçük kaseler veya çukur tabağa alın.","İsterseniz kaşıkla hafifçe karıştırarak mermer desen oluşturun.","Sıcak ekmekle servis edin — veya ikisini karıştırmadan daldırarak yeyin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 5, 0, 4, 'Kolay', false, true, false, 4.7, 0, 'published',
 'Tahin Pekmez — Şanlıurfa Kahvaltısının Sembolü',
 'Şanlıurfa kahvaltısının vazgeçilmezi tahin ve pekmez nasıl servis edilir? Geleneksel sunum önerileri.',
 NOW(), NOW()),

(gen_random_uuid(), 'oruk', 'Oruk',
 'İçli köftenin Şanlıurfa versiyonu olan oruk, dışı bulgur hamuru içi kıymalı dolma şeklinde hazırlanır. Genellikle haşlanarak veya kızartılarak servis edilir.',
 '{"2 su bardağı ince bulgur","200g dana kıyma (iç harcı için)","1 soğan","2 yemek kaşığı domates salçası","1 çay kaşığı pul biber","1 demet maydanoz","Tuz, karabiber","1 çorba kaşığı sade yağ"}',
 '{"Bulguru az su ile ıslatıp 30 dakika bekletin, tuzla yoğurun.","İç harcı için kıymayı yağda kavurun, soğan, salça ve baharatları ekleyin, maydanozla karıştırın.","Bulgur hamurunu yumurta büyüklüğünde parçalar alın, avuç içinde oyuk açın.","İç harcı yerleştirin, kapatıp oval şekil verin.","Tuzlu suda 15 dakika haşlayın ya da yağda kızartın."}',
 '/images/hero/sanliurfa-editorial-food.webp', 45, 20, 6, 'Zor', true, false, false, 4.5, 0, 'published',
 'Oruk Tarifi — Şanlıurfa İçli Köftesi',
 'Şanlıurfa''ya özgü içli köfte olan oruk nasıl yapılır? Bulgur hamuru ve kıymalı iç harç ile hazırlanan geleneksel tarif.',
 NOW(), NOW()),

(gen_random_uuid(), 'cennet-corbasi', 'Cennet Çorbası',
 'Beyaz peynir, domates ve biber ile hazırlanan hafif Urfa çorbası. Yaz aylarında soğuk servis edilebildiği gibi kışın da sıcak içilir. Adını cennet bahçelerini çağrıştıran taze renginden alır.',
 '{"200g beyaz peynir","4 adet olgun domates","2 adet sivri biber","1 baş soğan","2 yemek kaşığı zeytinyağı","1 lt su veya tavuk suyu","Tuz, karabiber","Taze nane"}',
 '{"Domatesleri soyup küçük doğrayın, biberleri ince kıyın.","Zeytinyağında soğanı kavurun, domates ve biberi ekleyin, 5 dakika pişirin.","Su veya tavuk suyunu ekleyin, kaynayınca iyice ufalanmış beyaz peyniri ilave edin.","Kısık ateşte 10 dakika pişirin, taze nane ile servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 20, 4, 'Kolay', false, true, false, 4.3, 0, 'published',
 'Cennet Çorbası Tarifi — Urfa Beyaz Peynirli Çorba',
 'Şanlıurfa''ya özgü hafif beyaz peynirli cennet çorbası tarifi. Yaz ve kışın içilen geleneksel Urfa çorbası.',
 NOW(), NOW()),

(gen_random_uuid(), 'keshkek', 'Keşkek',
 'Düğün ve bayramlarda yapılan, buğday ve kuzu etinin saatlerce pişirildiği geleneksel toy yemeği. UNESCO somut olmayan kültürel miras listesinde yer alan bu yemek, toplu törenlerin simgesidir.',
 '{"500g kırık buğday (aşurelik)","500g kuzu but eti (kemikli)","2 lt su","100g tereyağı","Tuz","1 çay kaşığı karabiber","Üzeri için: eritilmiş tereyağı + pul biber"}',
 '{"Kırık buğdayı bir gece önceden suya bırakın.","Kuzu etini tuzlu suda 2 saat haşlayın, kemiklerinden ayırın, suyu saklayın.","Et suyuna ıslak buğdayı ekleyin, kısık ateşte 1 saat daha pişirin.","Ara sıra tahta kaşıkla bastırarak buğdayı ezin, et lifleriyle karıştırın.","Tereyağı, tuz ve karabiberle son tat vermesini yapın.","Servis tabağına alıp üzerine kırmızı biberli tereyağı gezdirin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 30, 180, 8, 'Zor', false, false, true, 4.8, 0, 'published',
 'Keşkek Tarifi — UNESCO Miras Yemeği',
 'UNESCO somut olmayan kültürel miras listesinde yer alan keşkek nasıl yapılır? Kuzu eti ve buğday ile hazırlanan geleneksel düğün yemeği tarifi.',
 NOW(), NOW()),

(gen_random_uuid(), 'kusleme', 'Küşleme',
 'Haşlanmış kuzu budunun özel baharatlarla kaplı hâlde sunulduğu Urfa''nın geleneksel et yemeği. Sade pişirim tekniğiyle etin özgün tadını ön plana çıkarır.',
 '{"1 adet kuzu but (yaklaşık 2kg)","1 baş soğan","5 diş sarımsak","3 defne yaprağı","Tuz, karabiber","Servis için: kuru soğan, maydanoz, limon, pul biber"}',
 '{"Kuzu budunu soğan, sarımsak, defne ve tuzla bol suda koyun.","Orta ateşte 1.5-2 saat haşlayın, üzerindeki köpüğü alın.","Et yumuşayınca sudan çıkarın, kemiklerinden ayırın.","Kuru soğan ve maydanozla kıyılmış garnitürle servis edin, limon sıkın."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 120, 6, 'Kolay', false, false, false, 4.4, 0, 'published',
 'Küşleme Tarifi — Şanlıurfa Haşlama Et',
 'Şanlıurfa''nın geleneksel haşlama et yemeği küşleme nasıl yapılır? Sade pişirim tekniğiyle hazırlanan lezzet.',
 NOW(), NOW()),

(gen_random_uuid(), 'soganlı-kofte', 'Soğanlı Köfte',
 'İçine bolca kuru soğan katılarak hazırlanan ve fırında veya saçta pişirilen yöresel Urfa köftesi. Soğanın tatlılığı ve baharatların dengesi eşsiz bir aroma yaratır.',
 '{"500g kıyma","4 adet kuru soğan","3 diş sarımsak","2 yemek kaşığı salça","1 çay kaşığı kimyon","1 çay kaşığı pul biber","Tuz, karabiber","3 yemek kaşığı sıvıyağ"}',
 '{"Soğanları rendeye çekin ya da çok ince doğrayın, fazla suyunu sıkın.","Kıyma, soğan, sarımsak ve tüm baharatları iyice yoğurun.","Yağlanmış tepsiye oval şekil vererek dizin.","200°C fırında 25-30 dakika veya iki tarafı kızarıncaya kadar pişirin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 20, 30, 4, 'Kolay', true, false, false, 4.4, 0, 'published',
 'Soğanlı Köfte Tarifi — Urfa Yöresel Köfte',
 'Şanlıurfa''ya özgü soğanlı köfte tarifi. Fırında pişirilen yöresel köfte nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'nohutlu-pilav', 'Nohutlu Pilav',
 'Şanlıurfa sofralarında et yemeklerinin yanında sıklıkla sunulan, tereyağlı ve nohutlu pilav. Basit ama tok tutan bu pilav, düğün ve büyük sofraların vazgeçilmezidir.',
 '{"2 su bardağı baldo pirinç","1 su bardağı haşlanmış nohut","3 su bardağı et veya tavuk suyu","60g tereyağı","Tuz"}',
 '{"Pirinci yıkayıp tuzlu suda 30 dakika bırakın, süzün.","Tereyağını tencerede eritin, pirinci ekleyip cam gibi saydam olana kadar kavurun.","Et suyunu ekleyin, nohutları ilave edin, tuzunu ayarlayın.","Kaynayınca kapağı kapatın, kısık ateşte 18 dakika pişirin.","10 dakika demlenmeye bırakıp karıştırarak servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 40, 20, 6, 'Kolay', false, true, false, 4.5, 0, 'published',
 'Nohutlu Pilav Tarifi — Şanlıurfa Düğün Pilavı',
 'Şanlıurfa''nın vazgeçilmez nohutlu pilavı tarifi. Et suyuyla pişirilen tereyağlı pilav nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'sirden-dolmasi', 'Şirden Dolması',
 'Kuzunun mide zarına bulgur, kıyma ve baharatlardan oluşan iç harç doldurularak hazırlanan geleneksel Urfa yemeği. Hem görsellik hem lezzet açısından bayram sofralarının özel yemeğidir.',
 '{"1 adet kuzu şirdeni (mide zarı, temizlenmiş)","1 su bardağı bulgur","200g kıyma","2 soğan","1 yemek kaşığı salça","Maydanoz","Pul biber, karabiber, tuz","2 yemek kaşığı tereyağı"}',
 '{"Şirdeni bol suyla iyice yıkayın, içini tersine çevirin.","Bulguru kavurun, soğan, kıyma ve baharatlarla pişirin, soğutun.","İç harcı şirdene doldurun, ağzını ip veya şiş ile kapatın.","Tuzlu suda 1.5 saat kısık ateşte haşlayın.","Dilimleyerek, üzerine tereyağı gezdirip servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 40, 90, 6, 'Zor', true, false, false, 4.6, 0, 'published',
 'Şirden Dolması Tarifi — Geleneksel Urfa Yemeği',
 'Şanlıurfa''ya özgü şirden dolması nasıl yapılır? Kuzu midesi içine bulgur ve kıyma harcıyla doldurularak pişirilen geleneksel tarif.',
 NOW(), NOW()),

(gen_random_uuid(), 'incir-tatlisi', 'İncir Tatlısı',
 'Şanlıurfa''nın meşhur kuru inciriyle hazırlanan şerbetli tatlı. Fıstık veya cevizle doldurulmuş kuru incirler, gül suyu katkılı şerbete batırılarak sunulur.',
 '{"20 adet kuru Urfa inciri","100g antep fıstığı veya ceviz (iç)","2 su bardağı su","1.5 su bardağı toz şeker","1 tatlı kaşığı gül suyu","Kaymak veya dondurma (servis için)"}',
 '{"Kuru incirleri ılık suda 30 dakika yumuşatın.","Her incirin alt kısmından küçük kesik açın, fıstık veya ceviz doldurun.","Şeker ve suyu kaynatıp şerbet yapın, gül suyunu ekleyin.","Doldurulmuş incirleri şerbete daldırın, 10 dakika kısık ateşte pişirin.","Soğuk servis edin, yanında kaymak veya dondurma ile sunun."}',
 '/images/hero/sanliurfa-editorial-food.webp', 40, 15, 6, 'Kolay', false, true, true, 4.7, 0, 'published',
 'İncir Tatlısı Tarifi — Şanlıurfa Kuru İnciri ile',
 'Şanlıurfa''nın meşhur kuru inciriyle yapılan geleneksel incir tatlısı tarifi. Fıstıklı ve gül sulu şerbetli tatlı.',
 NOW(), NOW()),

(gen_random_uuid(), 'tepsi-boregi', 'Tepsi Böreği',
 'İnce yufkalarla hazırlanan, içine beyaz peynir ve maydanoz konan geleneksel Urfa tepsi böreği. Üzeri yumurta ve tereyağı karışımıyla kızartılır.',
 '{"6 adet ince yufka","300g beyaz peynir","1 demet maydanoz","3 yumurta","100ml süt","100g eritilmiş tereyağı","Pul biber (isteğe göre)"}',
 '{"Beyaz peyniri ufalayın, ince kıyılmış maydanoz ve pul biberle karıştırın.","Yumurta, süt ve erimiş tereyağını çırpın.","Tepsiye yağ sürün, 3 yufkayı alt alta, arasına peynir harcı koyarak dizin.","Kalan 3 yufkayı üste katplayın, üzerine yumurtalı karışım gezdirin.","190°C fırında 30-35 dakika, üzeri altın rengi olana kadar pişirin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 20, 35, 8, 'Orta', false, true, false, 4.6, 0, 'published',
 'Tepsi Böreği Tarifi — Urfa Peynirli Börek',
 'Şanlıurfa usulü peynirli tepsi böreği tarifi. Beyaz peynir ve maydanozlu geleneksel Urfa böreği nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'ayran-corbasi', 'Ayran Çorbası',
 'Sıcak yaz günlerinde serinletici, kışın ise ısıtıcı olan Urfa''nın geleneksel ayran çorbası. Yoğurt, nane ve nohut ile hazırlanan bu çorba, bölgenin hafızasında derin iz bırakmıştır.',
 '{"500g süzme yoğurt","1 lt su","1 su bardağı haşlanmış nohut","2 yumurta sarısı","2 yemek kaşığı un","Kuru nane, tuz","Üzeri için: pul biberli tereyağı"}',
 '{"Yoğurt, yumurta sarıları ve unu bir kapta iyice çırpın.","Su ekleyerek açın, tencereye alın, sürekli karıştırarak orta ateşte ısıtın.","Kaynamaya başlayınca 5 dakika daha pişirin, nohutları ekleyin.","Kuru nane ekleyip tuz ayarlayın.","Üzerine pul biberli tereyağı gezdirip servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 20, 4, 'Kolay', false, true, false, 4.4, 0, 'published',
 'Ayran Çorbası Tarifi — Serinletici Urfa Çorbası',
 'Şanlıurfa''nın geleneksel ayran çorbası nasıl yapılır? Yoğurt, nohut ve nane ile hazırlanan serinletici Urfa çorbası tarifi.',
 NOW(), NOW()),

(gen_random_uuid(), 'salgam-suyu', 'Şalgam Suyu',
 'Şanlıurfa ve Adana''da özellikle kebap yanında tercih edilen, şalgam turpu, mor havuç ve bulgurla fermente edilen geleneksel ekşili içecek. Ev yapımı tarifi daha zengin ve derin aromalıdır.',
 '{"4 adet şalgam turpu","3 adet mor havuç","2 yemek kaşığı kaya tuzu","1 yemek kaşığı nohut unu (maya için)","1.5 lt ılık su","Pul biber (isteğe göre)"}',
 '{"Şalgam ve havuçları yıkayıp küp doğrayın.","Büyük cam kavanozu sıcak suyla sterilize edin.","Sebzeleri kavanozu doldurun, tuz ve unu ekleyin.","Ilık suyu üzerine dökün, ağzını bez veya tülbent ile kapatın.","Serin ve karanlık bir yerde 4-7 gün mayalanmaya bırakın.","Tatlandıktan sonra süzerek şişeye alın, buzdolabında saklayın."}',
 '/images/hero/sanliurfa-editorial-food.webp', 30, 0, 8, 'Orta', false, true, false, 4.5, 0, 'published',
 'Şalgam Suyu Tarifi — Ev Yapımı Fermente İçecek',
 'Kebap yanında içilen geleneksel şalgam suyu nasıl evde yapılır? Mor havuç ve şalgamla fermente Urfa içeceği tarifi.',
 NOW(), NOW()),

(gen_random_uuid(), 'acili-ezme', 'Acılı Ezme',
 'Şanlıurfa sofralarının vazgeçilmez mezesi. Taze domates, biber ve bolca isot ile hazırlanan, kebapların yanında sunulan bu ezme, Urfa mutfağının en sade ama en karakteristik lezzetidir.',
 '{"4 adet olgun domates","3 adet sivri biber","1 soğan","2 yemek kaşığı isot (kuru Urfa biberi)","2 yemek kaşığı zeytinyağı","1 çay kaşığı tuz","Maydanoz, nane (isteğe göre)"}',
 '{"Domatesleri, biberleri ve soğanı çok ince doğrayın veya kıyın (blender''a atmayın, tekstür önemli).","Tüm malzemeleri derin bir kapta karıştırın.","İsot, zeytinyağı ve tuzu ekleyip harmanlayın.","En az 30 dakika dinlendirin ki lezzetler buluşsun.","Kebap, pide veya ekmek yanında servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 20, 0, 6, 'Kolay', true, true, false, 4.8, 0, 'published',
 'Acılı Ezme Tarifi — Urfa''nın Vazgeçilmez Mezesi',
 'Şanlıurfa''nın geleneksel acılı ezme tarifi. İsotlu ve taze domatesli kebap yanı meze nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'humus', 'Humus',
 'Nohut, tahin ve limonun buluştuğu bu Orta Doğu mezesi, Şanlıurfa mutfağında zeytinyağı ve pul biberle özel bir sunuma kavuşur. Ev yapımı humus markettekilerin çok önüne geçer.',
 '{"400g haşlanmış nohut","3 yemek kaşığı susam tahin","3 yemek kaşığı zeytinyağı","2 diş sarımsak","Yarım limon suyu","Tuz, kimyon","Üzeri için: zeytinyağı, pul biber, maydanoz"}',
 '{"Haşlanmış nohutları, tahin, sarımsak, limon suyu ve tuzla mutfak robotuna koyun.","Bir dakika çekin, pürüzsüz olana kadar devam edin.","Kıvam çok katıysa birkaç yemek kaşığı haşlama suyu ekleyin.","Derin tabağa alın, üzerine zeytinyağı, pul biber ve maydanoz gezdirin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 0, 4, 'Kolay', false, true, false, 4.6, 0, 'published',
 'Humus Tarifi — Urfa Usulü Ev Yapımı Nohut Ezmesi',
 'Urfa usulü ev yapımı humus tarifi. İsotlu ve zeytinyağlı Şanlıurfa humusu nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'hurma-tatlisi', 'Hurma Tatlısı',
 'Şanlıurfa''da özellikle Ramazan sofralarında hazırlanan, taze veya kuru hurma ile yapılan geleneksel tatlı. Basit malzemeler, derin bir lezzet.',
 '{"300g kuru veya taze hurma (çekirdeksiz)","100g ceviz veya antep fıstığı","2 yemek kaşığı tereyağı","1 çorba kaşığı bal","Tarçın","Servis için: kaymak veya dondurma"}',
 '{"Kuru hurmaları sıcak suda 10 dakika bekletip yumuşatın.","Hurmaları uzunlamasına keserek ortasına fıstık veya ceviz parçaları yerleştirin.","Tavada tereyağını eritin, hurmaları hafifçe kavurun.","Üzerine bal gezdirin, tarçın serpin.","Sıcak veya soğuk, yanında kaymakla servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 10, 4, 'Kolay', false, true, false, 4.5, 0, 'published',
 'Hurma Tatlısı Tarifi — Ramazan Sofrası',
 'Şanlıurfa Ramazan sofralarından hurma tatlısı tarifi. Fıstıklı ve ballı geleneksel hurma tatlısı nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'gozleme', 'Gözleme',
 'İnce lavaş hamurunun sacda pişirildiği, içine peynir, ıspanak veya patates konulan geleneksel yöresel lezzet. Şanlıurfa''da bazı semtlerde ev kadınları tarafından açık ateşte yapılır.',
 '{"2 su bardağı un","1 su bardağı ılık su","Yarım çay kaşığı tuz","Yarım çay kaşığı kuru maya","İç harcı: beyaz peynir + maydanoz veya ıspanak"}',
 '{"Un, su, tuz ve mayayı karıştırıp yumuşak bir hamur yapın, 30 dakika bekletin.","Hamuru ceviz büyüklüğünde parçalara ayırıp oklava ile ince açın.","Yarısına iç harcı yayın, diğer yarısı üstüne kapatın.","Kuru ya da az yağlı kızgın sacda iki tarafı kızarana dek pişirin.","Sıcak servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 40, 20, 6, 'Orta', false, true, false, 4.6, 0, 'published',
 'Gözleme Tarifi — Sacda Pişirilen Geleneksel Hamur İşi',
 'Geleneksel sacda gözleme tarifi. Peynirli ve maydanozlu, ince hamurlu Urfa gözlemesi nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'kilis-tava', 'Kilis Tava',
 'Şanlıurfa sınırı boyunca sevilen ve bölgede yaygınlaşan, domates, biber ve kuzu etiyle hazırlanan tava yemeği. Adını Kilis ilinden alan bu yemek, Urfa sofralarında da sık yer bulur.',
 '{"500g kuzu eti (küçük parça)","4 adet domates","4 adet yeşil sivri biber","3 diş sarımsak","2 yemek kaşığı tereyağı","Tuz, karabiber, pul biber"}',
 '{"Kuzu parçalarını yağda yüksek ısıda mühürleyin.","Biberleri ve domatesleri yenilecek büyüklükte doğrayın.","Et üzerine sarımsak, biber ve domatesleri ekleyin.","Tuz, karabiber, pul biber ekleyip orta ateşte 20-25 dakika pişirin.","Sıcak, yanında ekmek veya pilav ile servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 30, 4, 'Kolay', true, false, false, 4.7, 0, 'published',
 'Kilis Tava Tarifi — Sınır Mutfağından Kuzu Tava',
 'Şanlıurfa''da sevilen Kilis tava tarifi. Domates ve biberli kuzu eti tava nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'fistikli-sarma', 'Fıstıklı Sarma',
 'Asma yaprağına sarılan zeytinyağlı veya etli dolma, Şanlıurfa''da antep fıstığıyla yapılan özel versiyonuyla servis edilir. Düğün ve bayram sofralarının özel yemeğidir.',
 '{"30 adet taze veya salamura asma yaprağı","1.5 su bardağı baldo pirinç","200g kıyma (isteğe göre)","100g antep fıstığı","1 soğan","2 yemek kaşığı domates salçası","1 çay kaşığı pul biber","Zeytinyağı, tuz, karabiber"}',
 '{"Pirinci yıkayıp zeytinyağıyla kavurun, soğan, kıyma ve salçayı ekleyin, 5 dakika pişirin.","Fıstıkları ekleyip karıştırın, soğutun.","Her asma yaprağının içine bir tatlı kaşığı harç koyup sarın.","Tencereye sıkıca dizin, üzerine su ve zeytinyağı gezdirin.","45 dakika kısık ateşte pişirin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 45, 50, 8, 'Zor', false, false, false, 4.7, 0, 'published',
 'Fıstıklı Sarma Tarifi — Urfa Düğün Dolması',
 'Antep fıstıklı asma yaprağı sarması tarifi. Şanlıurfa düğün sofralarından fıstıklı dolma nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'aşure', 'Aşure',
 'On iki çeşit tahıl, baklagil ve meyvenin birlikte pişirildiği, Hz. Nuh''un gemisinden ilham alan geleneksel tatlı. Şanlıurfa''da muharrem ayında hazırlanan aşure komşulara dağıtılır.',
 '{"1 su bardağı buğday (haşlanmış aşurelik)","1 su bardağı nohut","1 su bardağı kuru fasulye","1 su bardağı pirinç","1 su bardağı kuru kayısı","1 su bardağı kuru üzüm","1 su bardağı incir (kıyılmış)","2 su bardağı toz şeker","Gül suyu, tarçın","Üzeri için: ceviz, nar tanesi, tarçın"}',
 '{"Tüm tahıl ve baklagilleri önceden ayrı ayrı haşlayın.","Büyük tencerede haşlanmış malzemeleri birleştirin, su ekleyin.","Şekeri ekleyip orta ateşte 30 dakika pişirin.","Kuru meyveler, gül suyu ve tarçını ekleyip 10 dakika daha pişirin.","Kaselere boşaltıp ceviz, nar ve tarçınla süsleyerek soğutun."}',
 '/images/hero/sanliurfa-editorial-food.webp', 60, 60, 16, 'Orta', false, true, true, 4.8, 0, 'published',
 'Aşure Tarifi — Muharrem Ayının Geleneksel Tatlısı',
 'Geleneksel Urfa aşuresi nasıl yapılır? On iki malzeme ile hazırlanan muharrem tatlısı tarifi.',
 NOW(), NOW()),

(gen_random_uuid(), 'mercimek-corbasi', 'Urfa Mercimek Çorbası',
 'Kırmızı mercimeğin tereyağı ve kırmızı biberle kavrulan soğanla buluştuğu, Şanlıurfa''ya özgü zengin mercimek çorbası. Standart mercimek çorbasından farklı olarak isot ve taze limon ile servis edilir.',
 '{"1.5 su bardağı kırmızı mercimek","1 soğan","2 diş sarımsak","2 yemek kaşığı tereyağı","1 yemek kaşığı domates salçası","1 çay kaşığı isot","1 lt su veya et suyu","Tuz, kimyon","Limon, kuru nane (servis için)"}',
 '{"Mercimeği yıkayın, soğan ve sarımsak ile et suyunda 20 dakika haşlayın.","Blenderdan geçirip pürüzsüz yapın.","Tereyağında salça ve isotu kavurun, çorbaya ekleyin.","Tuz ve kimyon ile tatlandırın, 5 dakika daha pişirin.","Kuru nane serpin, limon ile servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 30, 4, 'Kolay', true, true, false, 4.7, 0, 'published',
 'Urfa Mercimek Çorbası Tarifi — İsotlu Kırmızı Mercimek',
 'Şanlıurfa usulü isotlu mercimek çorbası tarifi. Standart mercimek çorbasından farkı nedir?',
 NOW(), NOW()),

(gen_random_uuid(), 'patlican-dolmasi', 'Patlıcan Dolması',
 'Közlenmiş patlıcanın içine kıymalı pirinç harcının doldurulduğu, fırında veya tencerede pişirilen geleneksel Urfa dolması. Domates sosunda pişmesi aromatik bir derinlik katar.',
 '{"6 adet orta boy patlıcan","300g kıyma","1 su bardağı baldo pirinç","1 soğan","2 yemek kaşığı domates salçası","Domates, biber (pişirme tabanı için)","Pul biber, karabiber, tuz","Maydanoz"}',
 '{"Patlıcanları közde veya gazocağında yakmadan kabuk sertleşene kadar pişirin.","Üst kısmını kesin, dikkatli oyarak içini boşaltın (tabanı ve duvarları sağlam kalmalı).","Kıyma, pirinç, soğan, salça ve baharatları karıştırıp iç harç yapın.","Patlıcanları harca doldurun, üstünü kapayın.","Domates ve biberden yapılan sos üzerine oturtun, 40 dakika orta ateşte pişirin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 40, 50, 4, 'Orta', true, false, false, 4.6, 0, 'published',
 'Patlıcan Dolması Tarifi — Urfa Usulü',
 'Şanlıurfa usulü patlıcan dolması tarifi. Kıymalı pirinç harcıyla doldurulup domates sosunda pişirilen dolma nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'ballı-ekmek', 'Ballı Ekmek',
 'Sacda pişirilen, üzerine tereyağı ve çiçek balı sürülen basit ama lezzetli Urfa kahvaltılık ekmeği. Günümüzde bazı geleneksel kahvaltı salonlarında hâlâ servis edilmektedir.',
 '{"2 su bardağı un","Yarım su bardağı su (ılık)","Yarım çay kaşığı tuz","Yarım çay kaşığı kuru maya","Yanında: tereyağı ve çiçek balı"}',
 '{"Un, tuz ve mayayı karıştırıp ılık su ile yumuşak hamur yapın.","Üzerini örtüp 45 dakika mayalanmaya bırakın.","Küçük bezeler yapıp oklava ile kalın ve yuvarlak açın.","Yağsız kızgın sacda iki tarafı pişirin, hafif şişmeli.","Sıcakken tereyağı ve bal sürüp servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 50, 15, 6, 'Kolay', false, true, false, 4.5, 0, 'published',
 'Ballı Ekmek Tarifi — Urfa Geleneksel Kahvaltı Ekmeği',
 'Sacda pişirilen geleneksel Urfa ballı ekmeği tarifi. Tereyağı ve bal ile kahvaltı ekmeği nasıl yapılır?',
 NOW(), NOW()),

(gen_random_uuid(), 'taze-fasulye', 'Zeytinyağlı Taze Fasulye',
 'Taze fasulye mevsiminde Urfa mutfağında sıklıkla hazırlanan zeytinyağlı bir yaz yemeği. Domates ve soğanla pişirilen bu yemek, soğuk servis edildiğinde de harika bir meze olur.',
 '{"500g taze fasulye","3 adet olgun domates","2 soğan","4 yemek kaşığı zeytinyağı","3 diş sarımsak","Tuz, karabiber"}',
 '{"Fasulyeleri ayıklayıp yıkayın, ikiye kırın.","Soğanları zeytinyağında kavurun, sarımsak ekleyin.","Doğranmış domatesleri ekleyin, 5 dakika pişirin.","Fasulyeleri ekleyip tuz ve karabiber koyun.","Yarım su bardağı su ilave edip kısık ateşte 30-35 dakika pişirin.","Sıcak veya soğuk servis edin."}',
 '/images/hero/sanliurfa-editorial-food.webp', 15, 40, 4, 'Kolay', false, true, false, 4.4, 0, 'published',
 'Zeytinyağlı Taze Fasulye Tarifi',
 'Yaz mutfağının vazgeçilmezi zeytinyağlı taze fasulye tarifi. Domates ve sarımsakla pişirilen sağlıklı yaz yemeği.',
 NOW(), NOW())

ON CONFLICT (slug) DO NOTHING;

SELECT COUNT(*) AS recipe_toplam FROM recipes WHERE status='published';
