-- Q3 2027 Etkinlikleri — 10 etkinlik (Temmuz–Eylül)

INSERT INTO events (id, title, slug, description, start_date, end_date, location, organizer, category, status, is_free, is_online, image_url, view_count, created_at, updated_at)
VALUES

(gen_random_uuid(),
'Şanlıurfa Uluslararası Turizm Şenliği 2027',
'sanliurfa-uluslararasi-turizm-senligi-2027',
'Şanlıurfa''nın tarihi mekanlarında üç günlük uluslararası turizm şenliği. Tur operatörleri, oteller ve rehberler için B2B bölümü ile birlikte halka açık aktiviteler; yöresel yemek, müzik ve kültürel gösteriler. Balıklıgöl, Kapalı Çarşı ve Urfa Kalesi''nde eş zamanlı programlar.',
'2027-07-04 09:00:00', '2027-07-06 22:00:00',
'Balıklıgöl ve Tarihi Çarşı Bölgesi, Şanlıurfa',
'Şanlıurfa İl Kültür ve Turizm Müdürlüğü',
'Festival', 'published', true, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Halfeti Yaz Akşamı Konserleri — Temmuz 2027',
'halfeti-yaz-aksami-konserleri-temmuz-2027',
'Halfeti''de Fırat kıyısında her Cumartesi gerçekleşen yaz akşamı açık hava konserleri. Urfa türküleri, makam müziği ve zaman zaman folk-rock. Gün batımından sonra başlayan konser saati saat 23:00''e kadar sürüyor. Konser alanına denk gelen tekne turları ''müzikli'' programa geçiyor.',
'2027-07-05 19:30:00', '2027-07-26 23:00:00',
'Halfeti Fırat Kıyısı Açık Hava Sahnesi',
'Halfeti Kültür Derneği',
'Sanat', 'published', true, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Göbeklitepe Anadolu Kültür Buluşması 2027',
'gobeklitepe-anadolu-kultur-bulusmasi-2027',
'Göbeklitepe''nin keşfedilişinin 32. yıl dönümüne özel iki günlük kültür buluşması. Arkeologlar, tarihçiler ve kültür insanları bir araya gelip Neolitik dönem hakkında paneller ve açık oturumlar yapıyor. Halka açık sabah turları, çocuklar için arkeoloji atölyeleri ve Göbeklitepe belgesel gösterimi.',
'2027-07-19 09:00:00', '2027-07-20 18:00:00',
'Göbeklitepe Ziyaretçi Merkezi ve Konferans Salonu',
'Kültür ve Turizm Bakanlığı & Harran Üniversitesi',
'Akademi', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Kapalı Çarşı Uzun Gece Alışveriş ve Kültür Festivali',
'kapali-carsi-uzun-gece-alisveris-kultur-2027',
'Şanlıurfa Kapalı Çarşısı''nda Temmuz''un özel gecesinde sabah 02:00''a kadar açık alışveriş ve kültür festivali. Bakırcılar, hasırcılar ve kuyumcular canlı gösterim, geleneksel mırra ikramı ve yerel müzik eşliğinde gece boyunca aktif. Her yıl Temmuz''da gerçekleşen bu etkinlik yerli ve yabancı ziyaretçilerin ilgisini çekiyor.',
'2027-07-12 18:00:00', '2027-07-13 02:00:00',
'Kapalı Çarşı ve Bedesten, Şanlıurfa',
'Şanlıurfa Esnaf ve Zanaatkarlar Odası',
'Kültür', 'published', true, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Birecik Kelaynak Son Gözlem Etkinliği — Ağustos 2027',
'birecik-kelaynak-son-gozlem-agustos-2027',
'Her yıl Eylül başında Kuzey Afrika''ya göç eden kelaynak kuşlarının Ağustos ayındaki son görünümleri için özel gözlem etkinliği. Birecik üreme istasyonunda uzman ornitologlar eşliğinde sabah erken başlayan gözlem turu. Yavru kelaynaklarının uçuş pratiklerini yakın mesafeden izleme fırsatı. Sınırlı kontenjan.',
'2027-08-10 05:30:00', '2027-08-10 11:00:00',
'Birecik Kelaynak Kuşu Üreme İstasyonu, Birecik',
'Doğa Koruma ve Milli Parklar Genel Müdürlüğü',
'Turizm', 'published', false, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Harran Geleneksel Müzik ve Kültür Festivali 2027',
'harran-geleneksel-muzik-kultur-festivali-2027',
'Harran kümbet evlerinin arasında iki günlük geleneksel müzik ve kültür festivali. Güneydoğu Türkiye ve Suriye''den saz, def ve ney ustalarının katıldığı konserler. Gündüz kümbet ev ziyaretleri ve rehberli tur; gece açık hava konserleri. Her Ağustos düzenlenen festival Harran''ın en renkli etkinliği.',
'2027-08-15 09:00:00', '2027-08-16 23:00:00',
'Harran Kümbet Evleri ve Açık Hava Sahnesi, Harran',
'Harran Kaymakamlığı & Kültür Vakfı',
'Festival', 'published', false, false,
'/uploads/places/harran.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Tektek Dağları Doğa Yürüyüşü ve Fotoğraf Turu',
'tektek-daglari-doga-yuruyusu-fotograf-2027',
'Karahantepe yakınındaki Tektek Dağları''nda rehberli doğa yürüyüşü ve fotoğraf turu. 8 km orta zorluk seviyesi; volkanik plato, step bitki örtüsü ve göçmen kuş gözlemi. Ağustos''ta sabah erken başlayan tur öğle öncesi tamamlanır. Yanında yeterli su ve krem şart.',
'2027-08-22 06:00:00', '2027-08-22 12:00:00',
'Tektek Dağları, Karaharabe Köyü yakını, Viranşehir',
'Şanlıurfa Doğa Sporları Kulübü',
'Turizm', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Urfa Sonbahar Gastronomi Turu 2027',
'urfa-sonbahar-gastronomi-turu-2027',
'Şanlıurfa mutfağının Eylül lezzetlerini keşfeden rehberli gastronomi turu. Kapalı Çarşı''dan isot ve baharat alışverişi; Meşhur Hacı Ekber Ciğercisi''nde tandır ciğer tasting; Tarihi Urfa Katmercisi''nde katmer; Balıklıgöl Kahvaltı Bahçesi''nde kapanış. Yaklaşık 4 saatlik tur, öğleden önce başlıyor.',
'2027-09-06 08:30:00', '2027-09-06 13:00:00',
'Kapalı Çarşı — Şanlıurfa Merkez',
'Urfa Mutfağı Derneği',
'Gastronomi', 'published', false, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Halfeti Sonbahar Tekne Turu Sezonu Etkinliği',
'halfeti-sonbahar-tekne-turu-sezonu-2027',
'Halfeti''de Eylül ayıyla birlikte açılan balık sezonu ve serinleyen havanın kutlaması. Sabah tekne turlarında Fırat''ın sonbahar renkleri ve kıyı restoranlarda taze balık. Günlük tur paketleri; Şanlıurfa merkezden kalkış dahil. Eylül–Kasım arası Halfeti''nin en keyifli dönemi.',
'2027-09-13 07:30:00', '2027-09-13 16:00:00',
'Halfeti İskelesi, Halfeti',
'Halfeti Turizm Kooperatifi',
'Turizm', 'published', false, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Karahantepe 2027 Kazı Sezonu Kapanış Konferansı',
'karahantepe-2027-kazi-sezonu-kapanis-konferansi',
'2027 Karahantepe kazı sezonunun kapanışında arkeologlar yılın bulgularını kamuoyuyla paylaşıyor. Kazı başkanı Prof. Dr. Necmi Karul ve ekibinin sunumları; yeni kabartmalar, yapı katmanları ve organik kalıntı analizleri hakkında bilgilendirme. Harran Üniversitesi konferans salonunda gerçekleşiyor, halka açık.',
'2027-09-27 09:00:00', '2027-09-27 17:00:00',
'Harran Üniversitesi Konferans Salonu, Şanlıurfa',
'Harran Üniversitesi Arkeoloji Bölümü',
'Akademi', 'published', true, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW())

ON CONFLICT (slug) DO NOTHING;

SELECT COUNT(*) AS etkinlik_toplam FROM events WHERE status='published';
SELECT MAX(start_date)::date AS son_etkinlik FROM events WHERE status='published';
