-- Q2 2027 Etkinlikleri — 10 etkinlik (Nisan–Haziran)

INSERT INTO events (id, title, slug, description, start_date, end_date, location, organizer, category, status, is_free, is_online, image_url, view_count, created_at, updated_at)
VALUES

(gen_random_uuid(),
'Halfeti Siyah Gül Festivali 2027',
'halfeti-siyah-gul-festivali-2027',
'Dünyada yalnızca Halfeti''de yetişen siyah güllerin açılma sezonuna özel yıllık festival. Tekne turları, gül bahçesi ziyaretleri, yerel sergi ve fotoğraf yarışması. Nisan''ın son haftası ile Mayıs''ın ilk haftasında yaklaşık 10 gün süren kutlama. Siyah gülün hikayesini anlatan rehberli turlar da etkinlik kapsamında.',
'2027-04-26 09:00:00', '2027-05-05 18:00:00',
'Halfeti İlçe Meydanı ve Fırat Kıyısı',
'Halfeti Kaymakamlığı & Turizm Kooperatifi',
'Festival', 'published', true, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Karahantepe Bahar Arkeoloji Turu 2027',
'karahantepe-bahar-arkeoloji-turu-2027',
'Göbeklitepe''nin kardeşi Karahantepe''de 2027 kazı sezonunun başlamasıyla birlikte arkeolog eşliğinde özel ziyaret. M.Ö. 9.000''e ait T-sütunları ve insan yüzü kabartmalarını yerinde inceleme. Sınırlı kontenjan, kayıt gerekli. Şanlıurfa merkezden ulaşım dahil.',
'2027-04-12 07:30:00', '2027-04-12 16:00:00',
'Karahantepe Arkeoloji Alanı, Viranşehir',
'Şanlıurfa Arkeoloji Derneği',
'Akademi', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Urfa Bahar Kültür ve Sanat Festivali 2027',
'urfa-bahar-kultur-sanat-festivali-2027',
'Şanlıurfa''nın tarihi mekanlarında açık hava konserleri, geleneksel el sanatları sergisi ve sıra gecesi gösterileri. Kapalı Çarşı ve Balıklıgöl çevresinde üç gün süren festival. Urfa türküleri, makam müziği ve yerel zanaatkarların atölye gösterimleri.',
'2027-05-03 10:00:00', '2027-05-05 22:00:00',
'Balıklıgöl ve Tarihi Çarşı Bölgesi, Şanlıurfa',
'Şanlıurfa Kültür ve Turizm İl Müdürlüğü',
'Kültür', 'published', true, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Halfeti Tekne Turu Sezonu Açılışı 2027',
'halfeti-tekne-turu-sezonu-acilisi-2027',
'Her yıl Mayıs başında gerçekleştirilen sezon açılış töreni. İlk günün tüm turlarına indirimli katılım fırsatı. Yerel müzik, ikramlar ve siyah gül sezonu açılış konuşması. Fırat üzerindeki tekne filosunun yeni sezon için hazırlıklarını yakından görme şansı.',
'2027-05-01 08:00:00', '2027-05-01 17:00:00',
'Halfeti İskelesi, Halfeti',
'Halfeti Turizm Kooperatifi',
'Turizm', 'published', false, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Birecik Kelaynak Kuşu Gözlem Festivali 2027',
'birecik-kelaynak-gozlem-festivali-2027',
'Dünyada 600''den az kalan kelaynak kuşlarının Birecik üreme istasyonunda yoğun görüldüğü Mayıs ayına özel gözlem etkinliği. Sabah erken başlayan rehberli kuş gözlemi, fotoğraf atölyesi ve Fırat kıyısında doğa yürüyüşü. Doğa fotoğrafçıları ve kuş gözlemcileri için eşsiz bir gün.',
'2027-05-17 05:30:00', '2027-05-17 14:00:00',
'Birecik Kelaynak Üreme İstasyonu, Birecik',
'Doğa Koruma ve Milli Parklar Genel Müdürlüğü',
'Turizm', 'published', true, false,
'/uploads/places/halfeti.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Göbeklitepe Bahar Fotoğraf Maratonu 2027',
'gobeklitepe-bahar-fotograf-maratonu-2027',
'Göbeklitepe''de gün doğumundan öğleye kadar süren 6 saatlik fotoğraf maratonu. Katılımcılar T-sütunları, kazı alanları ve çiçekli Harran Ovası manzaralarını çekiyor. Günün sonunda değerlendirme jürisi en iyi 10 fotoğrafı sergiliyor. Tüm seviyelere açık, ekipman sağlanmıyor.',
'2027-05-22 06:00:00', '2027-05-22 14:00:00',
'Göbeklitepe Arkeoloji Parkı',
'Şanlıurfa Fotoğrafçılar Derneği',
'Sanat', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Urfa Uluslararası Gastronomi Haftası 2027',
'urfa-uluslararasi-gastronomi-haftasi-2027',
'Şanlıurfa mutfağını dünyaya tanıtmayı amaçlayan haftalık festival. Usta aşçıların canlı gösterimleri, isot çeşitleri sergisi, geleneksel mırra ritüeli ve tatlı atölyeleri. Türkiye''nin dört bir yanından gastronomi meraklılarının katıldığı etkinlik, yabancı ziyaretçilere de açık.',
'2027-06-07 10:00:00', '2027-06-13 20:00:00',
'Tarihi Çarşı ve Gastronomi Merkezi, Şanlıurfa',
'Urfa Mutfağı Derneği & Şanlıurfa Ticaret Odası',
'Gastronomi', 'published', false, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Harran Yaz Kültür Geceleri 2027',
'harran-yaz-kultur-geceleri-2027',
'Harran kümbet evlerinin arasında, ay ışığında düzenlenen açık hava kültür geceleri. Urfa türküleri, kıssa anlatıcıları ve el sanatları sergileri. Haziran boyunca her Cuma ve Cumartesi akşamı düzenleniyor. Yöresel ikramlarla zenginleştirilen dört saatlik gece programı.',
'2027-06-06 20:00:00', '2027-06-28 24:00:00',
'Harran Kümbet Evleri, Harran',
'Harran Kaymakamlığı',
'Kültür', 'published', true, false,
'/uploads/places/harran.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Şanlıurfa Geleneksel El Sanatları Pazarı 2027',
'sanliurfa-geleneksel-el-sanatlari-pazari-2027',
'Bakırcılık, hasır dokuma, taşbaskı ve geleneksel Urfa işlemeciliği ustalarının bir araya geldiği açık hava pazarı. Zanaatkarlar çalışmalarını canlı gösteriyor, ziyaretçiler atölyelere katılabiliyor. Kapalı Çarşı''da iki günlük organizasyon.',
'2027-06-14 09:00:00', '2027-06-15 19:00:00',
'Kapalı Çarşı ve Bedesten, Şanlıurfa',
'Şanlıurfa Esnaf ve Zanaatkarlar Odası',
'Kültür', 'published', true, false,
'/uploads/places/balikligol.jpg', 0, NOW(), NOW()),

(gen_random_uuid(),
'Göbeklitepe Yaz Gece Turu 2027',
'gobeklitepe-yaz-gece-turu-2027',
'Göbeklitepe''de gün batımından sonra başlayan özel gece turu. Arkeoloji alanı spot ışıklamalarla aydınlatılıyor, rehberler 12.000 yıllık hikayeyi anlatıyor. Yoğun yaz kalabalığından uzak, etkileyici bir gece deneyimi. Haftanın iki günü, sınırlı kontenjan.',
'2027-06-20 19:30:00', '2027-06-20 22:30:00',
'Göbeklitepe Arkeoloji Parkı',
'Göbeklitepe Ziyaretçi Merkezi',
'Turizm', 'published', false, false,
'/uploads/places/gobeklitepe.jpg', 0, NOW(), NOW())

ON CONFLICT (slug) DO NOTHING;

SELECT COUNT(*) AS etkinlik_toplam FROM events WHERE status='published';
SELECT MAX(start_date)::date AS son_etkinlik FROM events WHERE status='published';
