import { describe, expect, it } from 'vitest';
import { GET as getOpenApi } from '../../pages/api/docs/openapi.json';

describe('openapi contract smoke', () => {
  it('includes normalized image fields for upload/favorites/follow/admin/reco/search flows', async () => {
    const response = await getOpenApi({} as any);
    expect(response.status).toBe(200);

    const spec = await response.json();
    expect(spec?.paths?.['/upload']).toBeDefined();
    expect(spec?.paths?.['/upload/{id}']).toBeDefined();
    expect(spec?.paths?.['/auth/register']).toBeDefined();
    expect(spec?.paths?.['/auth/me']).toBeDefined();
    expect(spec?.paths?.['/auth/logout']).toBeDefined();
    expect(spec?.paths?.['/auth/forgot-password']).toBeDefined();
    expect(spec?.paths?.['/auth/reset-password']).toBeDefined();
    expect(spec?.paths?.['/auth/2fa/setup']).toBeDefined();
    expect(spec?.paths?.['/auth/2fa/verify']).toBeDefined();
    expect(spec?.paths?.['/auth/2fa/disable']).toBeDefined();
    expect(spec?.paths?.['/featured-listings']).toBeDefined();
    expect(spec?.paths?.['/user/favorites']).toBeDefined();
    expect(spec?.paths?.['/user/profile']).toBeDefined();
    expect(spec?.paths?.['/user/subscription']).toBeDefined();
    expect(spec?.paths?.['/v2/favorites']).toBeDefined();
    expect(spec?.paths?.['/user/following/places']).toBeDefined();
    expect(spec?.paths?.['/places/trending-followers']).toBeDefined();
    expect(spec?.paths?.['/user/visits']).toBeDefined();
    expect(spec?.paths?.['/admin/dashboard']).toBeDefined();
    expect(spec?.paths?.['/admin/analytics']).toBeDefined();
    expect(spec?.paths?.['/admin/users']).toBeDefined();
    expect(spec?.paths?.['/recommendations/hybrid']).toBeDefined();
    expect(spec?.paths?.['/search/advanced']).toBeDefined();
    expect(spec?.paths?.['/search/suggestions']).toBeDefined();
    expect(spec?.paths?.['/search/trending']).toBeDefined();
    expect(spec?.paths?.['/search/history']).toBeDefined();
    expect(spec?.paths?.['/billing/checkout']).toBeDefined();
    expect(spec?.paths?.['/subscriptions/checkout']).toBeDefined();
    expect(spec?.paths?.['/subscriptions/tiers']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/photos']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/followers']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/like']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/share']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/visit']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/badges']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/analytics']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/availability']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/promotions']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/review-analytics']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/rating-distribution']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/request-verification']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/follow']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/verification']).toBeDefined();

    expect(spec?.components?.schemas?.UploadPhoto?.properties?.image_url).toBeDefined();
    expect(spec?.components?.schemas?.UploadPhoto?.properties?.thumbnail_url).toBeDefined();
    expect(spec?.components?.schemas?.FavoritePlace?.properties?.image_url).toBeDefined();
    expect(spec?.components?.schemas?.FollowedPlace?.properties?.image).toBeDefined();
    expect(spec?.components?.schemas?.FollowedPlace?.properties?.thumbnail).toBeDefined();
    expect(spec?.components?.schemas?.AdminDashboardTopPlace?.properties?.image_url).toBeDefined();
    expect(spec?.components?.schemas?.AdminDashboardTopPlace?.properties?.thumbnail_url).toBeDefined();
    expect(spec?.components?.schemas?.RecommendationPlace?.properties?.image_url).toBeDefined();
    expect(spec?.components?.schemas?.SearchAdvancedResult?.properties?.image_url).toBeDefined();
    expect(spec?.components?.schemas?.PlacePhotosResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceLikeGetResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceLikeMutationResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceShareGetResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceSharePostResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceFollowResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceVerificationResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceBadgesResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceAnalyticsResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlacePromotionsResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceAvailabilityResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceReviewAnalyticsResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceRatingDistributionResponse).toBeDefined();
    expect(spec?.components?.schemas?.PlaceRequestVerificationResponse).toBeDefined();
    expect(spec?.components?.schemas?.Error).toBeDefined();
    expect(spec?.components?.schemas?.ErrorBasic).toBeDefined();
    expect(spec?.components?.schemas?.ErrorFlagged).toBeDefined();
    expect(spec?.components?.schemas?.ErrorApi).toBeDefined();
    expect(Array.isArray(spec?.components?.schemas?.Error?.oneOf)).toBe(true);
    expect(spec?.components?.schemas?.Error?.oneOf?.length).toBe(3);
    expect(
      spec?.paths?.['/auth/login']?.post?.responses?.['401']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorBasic');
    expect(
      spec?.paths?.['/user/favorites']?.get?.responses?.['401']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorBasic');
    expect(
      spec?.paths?.['/v2/favorites']?.get?.responses?.['401']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorFlagged');
    expect(
      spec?.paths?.['/user/following/places']?.get?.responses?.['401']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/search/advanced']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/billing/checkout']?.post?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/subscriptions/checkout']?.post?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/photos']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/followers']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/like']?.post?.responses?.['401']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/share']?.post?.responses?.['401']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/visit']?.post?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/badges']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/analytics']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/availability']?.get?.responses?.['400']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/promotions']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/review-analytics']?.get?.responses?.['403']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/rating-distribution']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/request-verification']?.post?.responses?.['409']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/photos']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlacePhotosResponse');
    expect(
      spec?.paths?.['/places/{id}/like']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceLikeGetResponse');
    expect(
      spec?.paths?.['/places/{id}/share']?.post?.responses?.['201']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceSharePostResponse');
    expect(
      spec?.paths?.['/places/{id}/follow']?.post?.responses?.['201']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceFollowResponse');
    expect(
      spec?.paths?.['/places/{id}/verification']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceVerificationResponse');
    expect(
      spec?.paths?.['/places/{id}/badges']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceBadgesResponse');
    expect(
      spec?.paths?.['/places/{id}/analytics']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceAnalyticsResponse');
    expect(
      spec?.paths?.['/places/{id}/promotions']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlacePromotionsResponse');
    expect(
      spec?.paths?.['/places/{id}/availability']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceAvailabilityResponse');
    expect(
      spec?.paths?.['/places/{id}/review-analytics']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceReviewAnalyticsResponse');
    expect(
      spec?.paths?.['/places/{id}/rating-distribution']?.get?.responses?.['200']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceRatingDistributionResponse');
    expect(
      spec?.paths?.['/places/{id}/request-verification']?.post?.responses?.['201']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/PlaceRequestVerificationResponse');
    expect(
      spec?.paths?.['/places/{id}/follow']?.post?.responses?.['409']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/places/{id}/verification']?.get?.responses?.['500']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorApi');
    expect(
      spec?.paths?.['/admin/dashboard']?.get?.responses?.['401']?.content?.['application/json']?.schema?.$ref
    ).toBe('#/components/schemas/ErrorBasic');

    expect(spec?.paths?.['/auth/login']?.post?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/auth/login']?.post?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/auth/register']?.post?.responses?.['201']).toBeDefined();
    expect(spec?.paths?.['/auth/register']?.post?.responses?.['409']).toBeDefined();
    expect(spec?.paths?.['/places']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/places']?.post?.responses?.['400']).toBeDefined();
    expect(spec?.paths?.['/places']?.post?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/places']?.post?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/places/{id}']?.get?.responses?.['400']).toBeDefined();
    expect(spec?.paths?.['/places/{id}']?.get?.responses?.['404']).toBeDefined();
    expect(spec?.paths?.['/places/{id}']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/photos']?.get?.responses?.['404']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/photos']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/followers']?.get?.responses?.['404']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/followers']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/like']?.get?.responses?.['400']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/like']?.post?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/share']?.get?.responses?.['400']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/share']?.post?.responses?.['201']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/visit']?.post?.responses?.['201']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/visit']?.post?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/badges']?.get?.responses?.['404']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/analytics']?.get?.responses?.['403']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/analytics']?.get?.responses?.['404']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/availability']?.get?.responses?.['200']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/availability']?.get?.responses?.['404']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/promotions']?.get?.responses?.['404']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/review-analytics']?.get?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/review-analytics']?.get?.responses?.['403']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/rating-distribution']?.get?.responses?.['200']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/request-verification']?.post?.responses?.['201']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/request-verification']?.post?.responses?.['409']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/follow']?.post?.responses?.['201']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/follow']?.delete?.responses?.['200']).toBeDefined();
    expect(spec?.paths?.['/places/{id}/verification']?.get?.responses?.['200']).toBeDefined();
    expect(spec?.paths?.['/search']?.get?.responses?.['400']).toBeDefined();
    expect(spec?.paths?.['/search']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/billing/checkout']?.post?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/billing/checkout']?.post?.responses?.['422']).toBeDefined();
    expect(spec?.paths?.['/billing/checkout']?.post?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/subscriptions/checkout']?.post?.responses?.['201']).toBeDefined();
    expect(spec?.paths?.['/subscriptions/checkout']?.post?.responses?.['422']).toBeDefined();
    expect(spec?.paths?.['/subscriptions/tiers']?.get?.responses?.['200']).toBeDefined();

    expect(spec?.paths?.['/admin/dashboard']?.get?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/admin/dashboard']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/recommendations/hybrid']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/search/advanced']?.get?.responses?.['400']).toBeDefined();
    expect(spec?.paths?.['/search/advanced']?.get?.responses?.['500']).toBeDefined();
    expect(spec?.paths?.['/user/favorites']?.get?.responses?.['401']).toBeDefined();
    expect(spec?.paths?.['/user/visits']?.get?.responses?.['401']).toBeDefined();
  });
});
